### ISSUE TITLE
Software Design: Sequence Diagram

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#107]
### Issue Description

As discussed in the extra meeting on Tuesday, we will complete sequence diagrams on [Lucidchart](https://lucid.app/lucidchart/12990ace-9701-4be5-8ec5-cd83aebead91/edit?invitationId=inv_b9ba75d9-be43-49fd-9fcc-08c90d5c7fd8). Everyone has various tasks on the diagram.

According to meeting notes on Discord channel, tasks are distributed like below:
- [x] [Login](https://github.com/bounswe/bounswe2022group2/issues/109) - @bahricanyesil 
- [x] [Registration](https://github.com/bounswe/bounswe2022group2/issues/108) - @bahricanyesil 
- [x] [Chat](https://github.com/bounswe/bounswe2022group2/issues/114)- @mbatuhancelik 
- [x] [Search Course](https://github.com/bounswe/bounswe2022group2/issues/113) - @xltvy 
- [x] [Search User](https://github.com/bounswe/bounswe2022group2/issues/112) - @xltvy 
- [x] [Create Course](https://github.com/bounswe/bounswe2022group2/issues/115) - @hasancan-code 
- [x] [Edit Profile Page](https://github.com/bounswe/bounswe2022group2/issues/120) - @codingAku 
- [x] [Create Event](https://github.com/bounswe/bounswe2022group2/issues/121) - @egemenatikk 
- [x] [Take Note](https://github.com/bounswe/bounswe2022group2/issues/117) - @ezgy 
- [x] [Annotate](https://github.com/bounswe/bounswe2022group2/issues/118) - @onurkomurcu 
- [x] [Admin Edits Course](https://github.com/bounswe/bounswe2022group2/issues/119) - @onurkomurcu 
- [x] [Take Course](https://github.com/bounswe/bounswe2022group2/issues/116) - @surmelienes1 
- [x] [Join Event](https://github.com/bounswe/bounswe2022group2/issues/122) - @egemenatikk 

### Step Details

Steps that will be performed:

- Every responsible should share an info about the sections/parts s/he will perform.
- Every responsible should mention the sub-issue that contains the details of his/her work, if a sub-issue is created.
- Every responsible should mention this issue in the description of his/her sub-issue, if a sub-issue is created.

### Final Actions

After all sequence diagrams are created, this issue content and the content of the sequence diagram as whole will be reviewed by @xltvy.

### Deadline of the Issue

11.04.2022 - Monday - 10.00

### Reviewer

Altay Acar

### Deadline for the Review

11.04.2022 - Monday - 12.00

**Comment by bahricanyesil** [comment]
I completed the registration part of the sequence diagram. I will close its issue after the review process. You can see the details of that part from the issue #108.

**Comment by bahricanyesil** [comment]
I completed the login part of the sequence diagram. I will close its issue after the review process. You can see the details of that part from the issue #109.

**Comment by surmelienes1** [comment]
I finished my work on the take course part of our sequence diagram. The related issue will be closed after it is reviewed by @onurkomurcu. The details of the take course part can be found in the issue #116.

**Comment by egemenatikk** [comment]
I completed the Create Event part of the sequence diagram. I will close its issue after the review process. You can see the details of that part from the issue #121 .

**Comment by egemenatikk** [comment]
I completed the Join Event part of the sequence diagram. I will close its issue after the review process. You can see the details of that part from the issue #122 .

**Comment by bahricanyesil** [comment]
Waiting for the closing of all sub-issues related to specific parts of the sequence diagram.

**Comment by bahricanyesil** [comment]
Waiting for #117 to be closed.

**Comment by onurkomurcu** [comment]
Sequence diagram was finalized and added to corresponding wiki [page](https://github.com/bounswe/bounswe2022group2/wiki/Sequence-Diagram). I have arranged all sequence diagrams to have the same template. Thank you all for your work!
