### ISSUE TITLE
Milestone-1: Creating Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#123]
### Issue Description

We will be creating a responsibility assignment matrix for milestone report as discussed in regular meeting of week 6.

To accomplish this, I will be create the table in google sheets with columns as members and rows as tasks, then each member fill up their column. Once I created the sheet, I'll be sharing an edit link and tag everyone in the team in a comment as a checklist.

### Step Details

Steps that will be performed:
- [x] List and categorize the tasks achieved by members
- [x] Create the R.A.M table
- [x] Create a checklist to track who filled their columns. #123 
- [x] Tag members so that they fill their columns

### Final Actions

After the RAM is completed, it should be displayed in milestone report 1.

### Deadline of the Issue

12 - 04 - 2022 Tuesday 10:00

### Reviewer

Egemen Atik

### Deadline for the Review

14 - 04 - 2022 Thursday 20:00

**Comment by mbatuhancelik** [comment]
I begin by determining contents of the RAM. To do so, I scanned our issues and meeting notes.  
After the contents are approved, I will create the table for everyone to fill their columns.

I determined contents of the R.A.M as following:

Meetings and Communication

- Creating the Communication Plan
- Managing the discord channel
- Taking and documenting meeting notes for 1st regular meeting
- Taking and documenting meeting notes for 2nd regular meeting
- Taking and documenting meeting notes for 3rd regular meeting
- Taking and documenting meeting notes for 4th regular meeting
- Taking and documenting meeting notes for 5th regular meeting
- Taking and documenting meeting notes for use case diagram meeting
- Taking and documenting meeting notes for class diagram meeting
- Taking and documenting meeting notes for 6th regular meeting

Requirements:

- Determining Base Features
- Research about similar products
- Come up with questions about requirements to ask to customer
- Organize wiki page for questions about requirements
- Determining user requirements
- Determining system requirements
- Determining non-functional requirements
- Preparing Glossary

Scenarios and Mockups

- Scenario: Registered Lecturer
- Scenario: Unregistered Learner
- Scenario: Creating Event
- Creating general template for Mockups@ Figma
- Mockup: Registered Lecturer
- Mockup: Unregistered Learner
- Mockup: Creating Event

Design Diagrams:

- Use Case Diagram
- Class Diagram
- Sequence Diagram: Login and Registration
- Sequence Diagram: Chat
- Sequence Diagram: Search Course
- Sequence Diagram: Search User
- Sequence Diagram: Create Course
- Sequence Diagram: Edit Profile Page
- Sequence Diagram: Create Event
- Sequence Diagram: Take Note
- Sequence Diagram: Annotate
- Sequence Diagram: Admin Edits Course
- Sequence Diagram: Take Course
- Sequence Diagram: Join Event
- Adding Diagrams to wiki

Repository:

- Creating Issue Labels
- Creating Issue Template
- Managing Wiki Home Page
- Managing Readme
- Creating template about personal wiki pages
- Creating template about meeting notes
- Creating personal wiki pages

Research:

- Researching about GitHub repositories
- Documenting the research about GitHub Repositories
- Researching about semantic search
- Documenting research about semantic search
- Researching about W3 Web annotation model
- Documenting W3 Web annotation model research
- Researching about git
- Documenting research about git
- Researching about similar products
- Documenting the research about similar products

**Comment by mbatuhancelik** [comment]
Review is requested from @egemenatikk to continue creating the table!

**Comment by mbatuhancelik** [comment]
As we discussed in meeting 6.1, we will be keeping RAM as detailed as possible. I will begin creating excel table with the list of responsibilities given above.

**Comment by mbatuhancelik** [comment]
I created RAM sheet, you can access it from [here](https://docs.google.com/spreadsheets/d/1snznWp1hqTykJNHQT01oZ3V-j5Ejx8W2CwYlnXXIs-k/edit?usp=sharing)

**Comment by mbatuhancelik** [comment]
Adding a checklist to keep track of who filled their columns in RAM.
Please tick your tickbox when you are done filling your column.

- [ ] @xltvy 
- [ ] @egemenatikk 
- [ ] @ezgy 
- [ ] @mbatuhancelik 
- [ ] @hasancan-code 
- [ ] @onurkomurcu 
- [ ] @ahmet633 
- [ ] @codingAku 
- [ ] @surmelienes1 
- [ ] @bahricanyesil

**Comment by bahricanyesil** [comment]
Thank you for your work @mbatuhancelik! I added the following rows since I thought that they are missing:

1. Delete account requirements
2. Sequence Diagram - Create Event

**Comment by bahricanyesil** [comment]
> Adding a checklist to keep track of who filled their columns in RAM. Please tick your tickbox when you are done filling your column. If you think one of your responsibilities are missing, feel free to add a row to the matrix but please also comment here what have you added.
> 
> * [ ]  @xltvy
> * [ ]  @egemenatikk
> * [ ]  @ezgy
> * [ ]  @mbatuhancelik
> * [ ]  @hasancan-code
> * [ ]  @onurkomurcu
> * [ ]  @ahmet633
> * [ ]  @codingAku
> * [ ]  @surmelienes1
> * [x]  @bahricanyesil

I think it will be better if you can open a new issue related to filling the RAM. If we do like that, we can track the responsibility of each team member and tasks in GitHub seems in the issue so that we will not close until all tasks are done. I guess adding a checklist as a comment cannot be seen from the outside of the issue.

**Comment by mbatuhancelik** [comment]
Sure, migrating the checklist.

**Comment by mbatuhancelik** [comment]
Sections suggested by @xltvy  are added. I believe RAM covers everything we have done up to now and most people have completed their columns, so closing the issue.
