### ISSUE TITLE
Milestone-1: Writing the Forward Plan Part

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#127]
### Issue Description

We went over the first milestone assignment description pdf in our regular meeting of week 6. We decided the sub-titles/sub-tasks that should be included in the milestone report as to be compatible with the ones indicated in the pdf.

- This is a sub-issue of the main ["Documenting Milestone Report 1" issue](https://github.com/bounswe/bounswe2022group2/issues/128).
- There is a main title at the very first part of the milestone report, which is named as "Executive Summary". We have determined separate subtitles under this main title and one of them is "Forward Plan".
- I will be writing the content of this sub-section and will be sharing the written texts as I progress under this issue as comments, you can track my progress.

### Step Details

Steps that will be performed:

- [x] Go over the project description pdf, our requirements and other related wiki pages.
- [x] Write the content of the Forward Plan part.
- [ ] Receive review from @onurkomurcu and update the content accordingly.
- [ ] Make necessary final updates by analyzing our project plan.

### Final Actions

After I wrote and shared the texts, reviewer (@onurkomurcu) will be reviewing them and I will be doing necessary updates accordingly.

Finally, after all steps including the review are finalized, I will add the final version to the milestone report.

### Deadline of the Issue

13.03.2022 - Wednesday - 17:00

### Reviewer

Onur Kömürcü

### Deadline for the Review

14.03.2022 - Thursday - 20:00

**Comment by bahricanyesil** [comment]
## Info

- I wrote the whole forward-plan section. It is now finalized and ready to be reviewed by @onurkomurcu. We can also benefit from this text while creating our project plan just as I will benefit from the project plan to update this one, they are closely related to each other. Here's the text:

### **Forward Plan**

At the very first stage of our future plan, we will be implementing a practice app related to our main project (which includes similar sub-features) to experience the collaborative work and have a better vision of the future app development processes. Apart from this, we created our project plan with all details, determined our goals, and added them to this document under the “Project Plan” title. It is obvious that something can change on the road in the future according to our progress, and the feedback we received just as it happens in every project. However, we tried to create a followable plan and determined our base steps in a well-founded manner.

We will continue to follow our communication plan (regular meetings every Thursday) just as before since we think that it was efficient until now. We will be continuing to actively participate in the PS hours and communicate with our TA to ask questions, receive feedback and discuss ambiguous points. Just as happened before, we may arrange additional meetings in some weeks regarding some topics according to the requirements of the tasks, and the urgency of the issues.

To tell the truth, we feel excited to get closer and closer to the implementation part of the project. We are glad that the period when we put something out and get motivated by the outputs we get is coming. We will be continuing to learn software development skills also in the development phase since it is an endless learning process. We will explore new useful and helpful tools and use them in our project development process just as we did before (like Lucidchart).

From now on, we will be starting to plan and create the aspect-specific parts of the project by also organizing specific teams for each of them. Those teams mainly will be consisting of Android (or Hybrid according to the technology preference), web (front-end), and back-end parts. However, this division of responsibilities and working as a sub-team in addition to the work progress handled as the whole team is the topic the later of this semester. Belong these, we will also determine the technologies, programming languages, services, tools, and APIs that we will be using.

We are a group that gets along well, finishes the tasks quickly on time, and communicates without a problem with each other. So, we believe that at the end of a great development process, we will put a valuable project.

**Comment by bahricanyesil** [comment]
I added this part to our [milestone report](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit). I will update the content there if there will occur any changes here.

**Comment by onurkomurcu** [comment]
I have reviewed your work. It seems pretty good. Thank you for your work @bahricanyesil !
