### ISSUE TITLE
Documenting Milestone Report 1

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#128]
### Issue Description

After a great amount of work done related to our project, we will gather all the information related to our work and prepare a [**Milestone Report**](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit), which will be first installation of many to come. In the Milestone Report we will reflect upon the content of our repository and observations, the work we have done, tools we have used, and processes we have been through, alongside the current status of our project.

In our milestone report there will be 5 major deliverables:
1. D1- Project repository: up to date wiki pages (as usual constant gardening), issue
tracking.
2. D2- Requirements: Software Requirement Specification, Scenarios, and Mockups
3. D3- Software design documents in UML: use case, class, and sequence diagrams.
4. D4- Project plan & RAM (responsibility assignment matrix) & Communication plan
5. D5- Milestone report

Alongside the deliverables, our Milestone Report 1 will be consisted of below specified contents:
- [x] 1. [Title Page](https://github.com/bounswe/bounswe2022group2/issues/130) - @xltvy 
- [x] 2. [Table of Contents](https://github.com/bounswe/bounswe2022group2/issues/130) - @xltvy
- [x] 3. [Executive Summary](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit)
- [x] 3.1. [Introduction/Project Description](https://github.com/bounswe/bounswe2022group2/issues/126) - @bahricanyesil 
- [x] 3.2. [Project Status](https://github.com/bounswe/bounswe2022group2/issues/134) - @hasancan-code 
- [x] 3.3. [Forward Plan](https://github.com/bounswe/bounswe2022group2/issues/127) - @bahricanyesil 
- [x] 4. [List and Status of Deliverables](https://github.com/bounswe/bounswe2022group2/issues/140) - @surmelienes1
- [x] 5. Evaluation of Deliverables
- [x] 5.1. [Project Repository](https://github.com/bounswe/bounswe2022group2/issues/139) - @xltvy 
- [x] 5.2. Requirements - @mbatuhancelik 
- [x] 5.3. [Scenarios and Mockups](https://github.com/bounswe/bounswe2022group2/issues/135) - @codingAku 
- [x] 5.4. [Software Design Documents in UML](https://github.com/bounswe/bounswe2022group2/issues/138) - @surmelienes1
- [x] 5.5. [Communication Plan](https://github.com/bounswe/bounswe2022group2/issues/132) - @codingAku 
- [x] 5.6. Project Plan & RAM - @onurkomurcu & @egemenatikk & @mbatuhancelik 
- [x] 6. Evaluation of Tools and Processes
- [x] 6.1. [Evaluation of Tools](https://github.com/bounswe/bounswe2022group2/issues/141) - @ezgy 
    -  6.1.1. Discord - @ezgy  
    -  6.1.2. GitHub - @ezgy 
    - 6.1.3. Google Docs - @ezgy 
    - 6.1.4. Figma - @ezgy 
    - 6.1.5. Lucidchart - @ezgy 
    - 6.1.6. Slack - @ezgy 
- [x] 6.2. [Evaluation of Processes](https://github.com/bounswe/bounswe2022group2/issues/136) - @xltvy 
- [x] 6.2.1. [Team Meetings](https://github.com/bounswe/bounswe2022group2/issues/136) - @xltvy 
- [x] 6.2.2. [TA/Customer Meetings](https://github.com/bounswe/bounswe2022group2/issues/136) - @xltvy 
- [x] 6.2.3. [Issue Creation and Management](https://github.com/bounswe/bounswe2022group2/issues/136) - @xltvy 
- [x] 7. [Table of Work Done by Each Team Member](https://github.com/bounswe/bounswe2022group2/issues/131) - @bahricanyesil 
- [x] 7.1. [Altay Acar](https://github.com/bounswe/bounswe2022group2/issues/131) - @xltvy 
- [x] 7.2. Bahrican Yeşil - @bahricanyesil 
- [x] 7.3. [Ecenur Sezer](https://github.com/bounswe/bounswe2022group2/issues/131) - @codingAku 
- [x] 7.4. Egemen Atik - @egemenatikk 
- [x] 7.5. Ezgi Aysel Batı - @ezgy 
- [x] 7.6. Hasancan Erol - @hasancan-code 
- [x] 7.7. Mehmet Batuhan Çelik - @mbatuhancelik 
- [x] 7.8. [Muhammed Enes Sürmeli](https://github.com/bounswe/bounswe2022group2/issues/131) - @surmelienes1
- [x] 7.9. Onur Kömürcü - @onurkomurcu 
- [x] 8. Deliverables
- [x] 8.1. [Project Repository](https://github.com/bounswe/bounswe2022group2/issues/139) - @xltvy 
- [x] 8.2. Requirements - @mbatuhancelik 
- [x] 8.2.1. Glossary - @mbatuhancelik 
- [x] 8.2.2. Requirements - @mbatuhancelik 
- [x] 8.2.3. [Scenarios and Mockups](https://github.com/bounswe/bounswe2022group2/issues/135) - @codingAku 
- [x] 8.3. Software Design Documents in UML - @surmelienes1 
- [x] 8.3.1. Use-Case Diagrams - @surmelienes1 
- [x] 8.3.2. Class Diagrams - @surmelienes1 
- [x] 8.3.3. Sequence Diagrams - @surmelienes1 
- [x] 8.4. [Communication Plan](https://github.com/bounswe/bounswe2022group2/issues/132) - @codingAku 
- [x] 8.5. Project Plan - @onurkomurcu & @egemenatikk 
- [x] 8.6. [RAM (Responsibility Assignment Matrix)](https://github.com/bounswe/bounswe2022group2/issues/129) - @mbatuhancelik 

### Step Details

Steps that will be performed:
- [x] Under our GitHub repository a directory, named **_deliverables_** will be created.
- [x] Each team member will create the pages/subjects of **Milestone Report 1** they are assigned to.
- [x] Each work done will be reviewed by the whole team before finalizing.
- [x] Results will be gathered in the online document.
- [x] Document will be edited for better and more clear structure before submission.

### Final Actions

* After above specified work is done by each team member and the **Milestone Report 1** is ready, the document will be converted into PDF format.
* The PDF, named **_M1-Group-2-Deliverables_** will be submitted via Moodle and uploaded to the directory, **_deliverables_** under our GitHub repository.

### Responsible People

- [X] Bahrican Yesil
- [X] Egemen Atik
- [X] Altay Acar
- [X] Ezgi Aysel Batı
- [X] Muhammed Enes Sürmeli
- [X] Onur Kömürcü
- [X] Mehmet Batuhan Çelik
- [X] Hasan Can Erol
- [X] Ecenur Sezer

### Deadline of the Issue

15.04.2022 - Friday - 18.00

### Final To-Dos

- [x] Every responsible shared an info about the sections/parts s/he will perform.
- [x] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [x] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by bahricanyesil** [comment]
I took the responsibility of following sections and I added the corresponding links in the description too:

As two sub-sections of the main "Executive Summary" title:

- Introduction/Project Description: #126 
- Forward Plan: #127

**Comment by xltvy** [comment]
## Info:
I have created the online document and provided a title page, alongside the table of contents for our Milestone Report 1. Relevant issue can be reached from #130.

**Comment by bahricanyesil** [comment]
## Info

I took the responsibility of creating and tracking the "Table of Work Done by Each Team Member" section.

I created a sub-issue to track the people who have written their personal work and added to the table. You can view the issue for details: #131.

**Comment by codingAku** [comment]
Under Evaluation of Deliverables, I need Meeting Notes section to complete.

**Comment by hasancan-code** [comment]
I have completed the Project Status part of the job. You can check sub-issue #134.

**Comment by xltvy** [comment]
## Info
I took the responsibility of providing the **Evaluation of Deliverables** part of the _Milestone Report 1_ and the work can be tracked from this issue here #136.

**Comment by mbatuhancelik** [comment]
I created Ram under #123  and #129 is opened to fill up the table.

**Comment by surmelienes1** [comment]
## Info

I took responsibility for the following parts, and included the relevant links in the above issue description as well:

Below are two sub-sections for which I am responsible, along with their corresponding issues:

- Software Design Documents in UML: #138  
- List and Status of Deliverables: #140 

***
## Note
I finished my work on the Software Design Documents in UML and List and Status of Deliverables parts of our milestone report. The related issues will be closed after it is reviewed by @xltvy. The details of these parts can be found in the issues listed above.

**Comment by ezgy** [comment]
## Info  
 I will be working on the Evaluation of Tools (Title 4.1 in the Milestone Report-1). The issue regarding this task is #141.
*fyi:* to make  the checklist clear I've moved my subtasks under the main title checkbox and made them items instead of checkmarks. Individual progress can still be viewed under #141 as I have a checklist of steps there.

**Comment by egemenatikk** [comment]
## Info
I took the responsibility of providing the **Project Plan** part of the _Milestone Report 1_ and the work can be tracked from this issue here #137.

**Comment by onurkomurcu** [comment]
## Info
I took the responsibility of providing the **Project Plan** part of the _Milestone Report 1_ and the work can be tracked from this issue here #137.

**Comment by onurkomurcu** [comment]
Thank you all for your great effort!
