### ISSUE TITLE
Milestone-1: Creating the Online Document with Title Page and Table of Contents

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#130]
### Issue Description

As part of creating **Milestone Report 1**, I took the responsibility of creating the initial online document and sharing the link to the whole team.

* I have created the document and it can be viewed from this [link](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit?usp=sharing).
* I will add a title page and table of contents beforehand for the whole team to work tidy and clean.

### Step Details

Steps that will be performed:
- [x] Online document will be created.
- [ ] The edit link to the document will be shared.
- [ ] Title page for the document will be provided.
- [ ] Table of contents page for the document will be provided.

### Deadline of the Issue

12.04.2022 - Tuesday - 21.30
