### ISSUE TITLE
Milestone-1: Filling the Table of Work Done by Each Member Part

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#131]
### Issue Description

We went over the first milestone assignment description pdf in our regular meeting of week 6. We decided the sub-titles/sub-tasks that should be included in the milestone report as to be compatible with the ones indicated in the pdf. So, this issue is a sub-issue of #128. You can see the full table in the [Milestone Report-1](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) under the "Table of Work Done by Each Team Member" title.

We concluded that we should create a table for personal efforts and works of each member. Each team member will write his/her personal works done until now under this issue as comments and then check the checkbox containing his/her name.

### Step Details

Steps that will be performed:
- [x] I will create a base table in the [milestone report](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) and add my works to be an example for other teammates.
- [x] Every team member should write down the works s/he did until now item by item.
- [x] Every item should contain relevant links (wiki page, issue, document, and so on).
- [x] Every team member should fill the corresponding table in the milestone report with their works item by item.
- [x] After the all steps above, every person should share a screenshot of the part s/he completed and check the checkbox containing his/her name from the below list. 

### Final Actions

As I also indicated in the step details above, all team members will fill fill the table their individual parts they shared as a comment under this issue.

Since this is a part of the milestone report, after merging it to the report, we don't need to take any further action.

@onurkomurcu will be reviewing the issue and information shared by the team members to detect any possible problems.

### Responsible People

- [x] Bahrican Yesil - @bahricanyesil 
- [x] Egemen Atik - @egemenatikk 
- [x] Altay Acar - @xltvy 
- [x] Ezgi Aysel Batı - @ezgy 
- [x] Muhammed Enes Sürmeli - @surmelienes1 
- [x] Onur Kömürcü - @onurkomurcu 
- [x] Mehmet Batuhan Çelik - @mbatuhancelik 
- [x] Hasan Can Erol - @hasancan-code 
- [x] Ecenur Sezer - @codingAku 

### Deadline of the Issue

13.03.2022 - Wednesday - 22:00

### Reviewer

Onur Kömürcü

### Deadline for the Review

14.03.2022 - Thursday - 20:00

**Comment by bahricanyesil** [comment]
## Info

I created a table with the following columns, colors,
![Screen Shot 2022-04-13 at 11 22 59](https://user-images.githubusercontent.com/60237280/163133060-00f1e083-ffa2-4b75-a385-8384dd0eeba5.png)
 and example rows:

**Comment by bahricanyesil** [comment]
I completed my personal part in the Table of Work Done by Each Team Member. You can see it via [this link](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit). I'm also attaching the screenshot of it:

![Screen Shot 2022-04-13 at 12 13 51](https://user-images.githubusercontent.com/60237280/163142847-e74a70a0-ef04-45ff-9707-656949aedd0b.png)

![Screen Shot 2022-04-13 at 12 14 06](https://user-images.githubusercontent.com/60237280/163142892-6e091558-4beb-410a-a688-59a002b54e99.png)

Note: I will be adding the RAM and Project Plan works' issue and related documents afterwards when they are created by the responsibles.

**Comment by xltvy** [comment]
# Info
I have completed my personal part in the Table of Work Done by Each Team Member. You can see it via [this link](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/). Here is a screenshot of it:
<img width="383" alt="Ekran Resmi 2022-04-13 20 03 33" src="https://user-images.githubusercontent.com/68481602/163233154-36085bef-a064-4238-9959-2a6b91d5f5ae.png">
<img width="386" alt="Ekran Resmi 2022-04-13 20 03 53" src="https://user-images.githubusercontent.com/68481602/163233173-55c5029f-fce2-45ea-aff6-53f7c26f8d7f.png">

* Note: I will be adding the Project Plan related issues and documents afterward when they are created by the responsible people.

**Comment by codingAku** [comment]
I have completed my part of Table Work. Here's a screenshot of it. Original version can be found in Milestone-1 Report
![weektab](https://user-images.githubusercontent.com/64018144/163234010-3ec8bd76-4caf-482f-87e1-4db9768e4c64.jpg)
.

* Like my colleagues, Project Plan part is not completed yet.

**Comment by surmelienes1** [comment]
## Info

I completed my personal part in the Table of Work Done by Each Team Member. You can see it via [this link](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit). You can see below the screenshot of it:

<img width="774" alt="Screen Shot 2022-04-15 at 08 02 51" src="https://user-images.githubusercontent.com/74325266/163522929-3a1ac9f2-ef4b-4da7-bc6f-52827f3f78a4.png">
<img width="775" alt="Screen Shot 2022-04-15 at 08 03 21" src="https://user-images.githubusercontent.com/74325266/163523177-e9fdfeec-4102-4155-992f-41316a5389d2.png">
<img width="774" alt="Screen Shot 2022-04-15 at 08 03 32" src="https://user-images.githubusercontent.com/74325266/163523193-0a6c76c5-6495-4b43-9209-a23e06300d00.png">

***
## Note

I will be adding the Project Plan related issues and documents afterward when they are created by the responsible people.

**Comment by mbatuhancelik** [comment]
Part of the table considering me is now complete!
![image](https://user-images.githubusercontent.com/63948452/163540797-b55efd8d-1b0c-41a8-80ae-609203de63c2.png)
![image](https://user-images.githubusercontent.com/63948452/163540869-0050be49-1c8b-43a9-8426-c4bea19e6d66.png)
![image](https://user-images.githubusercontent.com/63948452/163540926-d46d79c8-1bb4-40e6-9178-1083d83d7d89.png)
![image](https://user-images.githubusercontent.com/63948452/163540942-ed854bfe-7312-4eb8-95a2-5f305356130f.png)

**Comment by ezgy** [comment]
I have filled the parts of work done by me in the table. Here is a screenshot:
![image](https://user-images.githubusercontent.com/56553280/163552558-e8e9c812-55c4-436f-88b1-0a16d116d73f.png)
![image](https://user-images.githubusercontent.com/56553280/163552589-a438707a-aca3-4520-a6b8-6673692b72b7.png)

**Comment by onurkomurcu** [comment]
## INFO

I have finished my part of the issue. It can be seen from following screenshots and milestone - 1 report which is provided in the issue description. 

<img width="741" alt="Ekran Resmi 2022-04-15 17 35 36" src="https://user-images.githubusercontent.com/92719802/163583882-9e3fb762-e29b-4a01-99c9-65c0b76bb596.png">
<img width="740" alt="Ekran Resmi 2022-04-15 17 35 45" src="https://user-images.githubusercontent.com/92719802/163583878-d98ce6ea-387c-4786-91bd-fb485e2889e3.png">
<img width="740" alt="Ekran Resmi 2022-04-15 17 35 53" src="https://user-images.githubusercontent.com/92719802/163583869-6ca30027-8c69-459c-8bdb-6386a9422e07.png">

**Comment by bahricanyesil** [comment]
Since all team members filled their own individual work summary parts, I'm now closing the issue.

**Comment by egemenatikk** [comment]
## INFO

I completed my part in the Table of Individual Work. Here is the screenshots of it:

<img width=850 alt="egemen_iw_1" src="https://user-images.githubusercontent.com/100771925/163589711-30aeb7ea-6adf-49ac-9c0e-682c68c18cfb.png">
<img width=850 alt="egemen_iw_2" src="https://user-images.githubusercontent.com/100771925/163589716-1a70c3e5-d828-446e-8429-fe32d145b3e1.png">
<img width=850 alt="egemen_iw_3" src="https://user-images.githubusercontent.com/100771925/163589717-3c2c8f59-593f-40e3-9e0c-569386c14bd0.png">
