### ISSUE TITLE
Milestone-1: Evaluation Of Deliverables - Communication Plan & Deliverables - Communication Plan

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#132]
### Issue Description

This is a sub-issue of #128.
In Meeting 6, sub-tasks and sub-sections of Milestone-1 Report has been decided. In work sharing, I have the task to complete 5.4. and 8.4. from the parent issue #128.

These are the Evaluation Of Deliverables -  Communication Plan & Deliverables - Communication Plan parts.

### Step Details

Steps that will be performed:
- [x] Go over our communication plan in our wiki.
- [x] Write the evaluation of the communication plan.
- [x] Create the table of the communication plan.

### Final Actions

After the steps are performed, the issue will be reviewed in @mbatuhancelik.

### Deadline of the Issue

13.04.2022 - Wednesday 17.00

### Reviewer

Altay Acar

### Deadline for the Review

13.04.2022 - Wednesday 18.00

**Comment by codingAku** [comment]
UPDATE:
Deliverable and Evaluation of Communication Plan has been made. The sections 3.5 and 6.4 in our [Milestone-1](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) are the related sections.

![com-eod](https://user-images.githubusercontent.com/64018144/163180344-940aff62-8839-49e5-af6b-5b375a1ba8b7.jpg)

![com-d](https://user-images.githubusercontent.com/64018144/163180365-6d38f78e-e185-47c5-81f0-f4b5d53527e9.jpg)

**Comment by xltvy** [comment]
Nice work! I think we may add our additional meetings that we held specifically about a topic such as UML diagrams besides our weekly regular meetings.

**Comment by codingAku** [comment]
> Nice work! I think we may add our additional meetings that we held specifically about a topic such as UML diagrams besides our weekly regular meetings.

Thank you. I have mentioned our extra meetings in section 3.5. Since they don't exist in our wiki page Communication Plan, I did not add them to the table in 6.4.

**Comment by xltvy** [comment]
> > Nice work! I think we may add our additional meetings that we held specifically about a topic such as UML diagrams besides our weekly regular meetings.
> 
> Thank you. I have mentioned our extra meetings in section 3.5. Since they don't exist in our wiki page Communication Plan, I did not add them to the table in 6.4.

Reasonable, closing #132
