### ISSUE TITLE
Milestone-1: Project Status

### ISSUE THREAD

**Issue by hasancan-code** [bounswe/bounswe2022group2#134]
### Issue Description

This is a sub-issue of #128.
After the sub-tasks have been determined in Meeting 6, I have the task to complete 3.2 which is project status part from parent issue #128. the 

### Step Details

Steps that will be performed:
- [x] Go over the whole project in order to determine what we have done until now.
- [x] Write the Project Status part of the Milestone-1 report.
- [x] Share the final version of the task as a comment.

### Final Actions

After the steps are performed, the issue will be reviewed by @ezgy 

### Deadline of the Issue

13.04.2022 - Wednesday - 17.00

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

13.04.2022 - Wednesday 18.00

**Comment by hasancan-code** [comment]
## Project Status 

Since the project starts,
* We have created our GitHub repository that we used all the time for cumulative improvement and communication along the way. At the beginning of the whole work, everyone in the group created their own wiki page and continue to update it every week because of weekly improvements. After that, we created our home page where all the links and information about the project can be found. 
* We all agreed on a communication plan and determined a communicator and weekly meeting time.
* We have researched other projects related to the education industry and documented our competitor analysis under our wiki page. 
* After the competitor analysis, we determined the base features of the project and then we determined the functional and non-functional requirements according to our past notes. 
* In order to validate these requirements, we prepared some questions about them and set a meeting with our customer. 
* We have created the mockup scenarios in order to make our project more understandable and show the customer how our project is going to look in certain scenarios. In the designing process of mockups, we created personas and scenarios, and we designed our mockups according to these. 
* We have created Class, Use-Case, and Sequence Diagrams in order to make our future improvement easier and how we will go further on the way.
* At the beginning of our diagram creation process, we design a Use-Case diagram according to the requirements. After that, we create our Class diagram and Sequence diagram respectively. In this process, we set lots of meetings to aim to review our tasks and plan future tasks. 
* We created RAM (Responsibility Assignment Matrix)  and our Project plan as a part of our Milestone-1 report. After the creation of the RAM table, everyone filled boxes according to their work done by now. We wrote what we do until now individually to put them in our Milestone-1 report.

**Comment by bahricanyesil** [comment]
I added this part to our [milestone report](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit). You can update the content there if there will occur any changes here.

**Comment by ezgy** [comment]
I have reviewed your project status report. I've cross-checked it with our repository and the status summary seems to include all the important work we have done. I like that the work was mentioned in chronological order as it makes it easier to track. Since the next item on the agenda(practice app) is mentioned in the future plans section, I think this section is a good representation of what we have done so far. As far as I can see there are no changes necessary, but I will keep this issue active until after the team review in the meeting - in case we come up with any improvements to be made.

**Comment by xltvy** [comment]
Closed #134
