### ISSUE TITLE
Milestone-1: Evaluation Of Deliverables - Scenarios and Mockups & Deliverables - Scenarios and Mockups

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#135]
### Issue Description

This is a sub-issue of #128.
In Meeting 6, sub-tasks and sub-sections of Milestone-1 Report has been decided. In work sharing, I have the task to complete Evaluation of Deliverables - Scenarios & Mockups(5.3) and 8.2.3. from the parent issue #128.

### Step Details

Steps that will be performed:
- [x] Go over scenarios and mockups in our wiki.
- [x] Write the evaluation of the Scenarios and Mockups.
- [x] Create the Deliverable part of Scenarios and Mockups.

### Final Actions

After the steps are complete, the issue will be reviewed in our milestone.  

### Deadline of the Issue

13.04.2022 - Wednesday 17.00

### Deadline for the Review

13.04.2022 - Wednesday 18.00

**Comment by codingAku** [comment]
UPDATE: Section 6.2.3 with its all sub-sections and Section 3.3 contain my work on our [Milestone-1](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit).

**Comment by xltvy** [comment]
I have reviewed the parts you have mentioned in the issue. It's all good! Closing #135
