### ISSUE TITLE
Milestone-1: Evaluation of Processes

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#136]
### Issue Description

* This is a sub-issue of #128 

I will be creating the **Evaluation of Processes** part of the _Milestone Report 1_.

In the Evaluation of Processes part we will convey our regular working process throughout the semester, which is divided into three main parts:
1. Regular team meetings
2. TA/Client meetings
3. Issue creation and management

I will outline each of the sub-topic mentioned above in our _Milestone Report 1_ document.

### Step Details

Steps that will be performed:
- [x] Check our meeting notes and issues in our repository.
- [x] Write outlines for each section.
- [x] Add them in the _Milestone Report 1_

### Final Actions

After the steps mentioned above are done, results will be reviewed before finalizing the evaluation of processes part of the _Milestone Report 1_

### Deadline of the Issue

13.04.2022 - Wednesday 17.00

### Reviewer

Ecenur Sezer

### Deadline for the Review

13.04.2022 - Wednesday 18.00

**Comment by xltvy** [comment]
## Info
* I have completed the evaluation of processes part of the _Milestone Report 1_ and added them to our online document.
* Here is a screenshot of the work below:
<img width="330" alt="Ekran Resmi 2022-04-13 18 34 24" src="https://user-images.githubusercontent.com/68481602/163217270-1f9af48f-41dc-43f3-ba67-c32f47366592.png">

* Now, it is ready for a review by @codingAku.

**Comment by codingAku** [comment]
Thank you for your hard work. I believe we can mention that our issues have one assignee and we use checklists to complete group issues which takes more than two people. Other than that, everything seems compatible with our discussions.

**Comment by xltvy** [comment]
> Thank you for your hard work. I believe we can mention that our issues have one assignee and we use checklists to complete group issues which takes more than two people. Other than that, everything seems compatible with our discussions.

* Thank you for your review. I added this text according to your feedback:
> Each issue is assigned to one member and when more than one member’s work is associated with the issue we use checklists to follow each member’s work. In those cases each member opens a sub-issue and connects it to the general issue for group work.

* Now, I believe this issue is resolved. So, I am closing it.
