### ISSUE TITLE
Milestone-1: Creating Project Plan

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#137]
### Issue Description

This issue is sub-issue of #128. We will do project plan for the Milestone report. The work is done with [ProjectLibre](https://www.projectlibre.com) app.

### Step Details

Steps that will be performed:
- [x] **Research** how to make project plan.
- [x] **Analyze** previous years repositories' project plan.
- [x] **Finalize** the project plan.
- [x] **Provide** the work here to be reviewed.

### Final Actions

After all work is done, project plan will be added to Milestone-1 report. 

### Responsible People

- [X] Egemen Atik 
- [X] Onur Kömürcü

### Deadline of the Issue

13.04.2022 - Wednesday 17.00

### Reviewer

Bahrican Yeşil

### Deadline for the Review

14.04.2022 - Thursday 20.00

### Final To-Dos

- [X] Every responsible shared an info about the sections/parts s/he will perform.

**Comment by egemenatikk** [comment]
I filled project plan up to Class Diagrams. Rest of our plan will be filled by @onurkomurcu.

**Comment by egemenatikk** [comment]
We created the project plan and added it to [Milestone Report-1](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) in the required place.

**Comment by onurkomurcu** [comment]
I filled the rest of the project plan. This issue can be closed now. Thank you for your great effort @egemenatikk.

**Comment by egemenatikk** [comment]
Thank you too, @onurkomurcu .
