### ISSUE TITLE
Milestone-1: Evaluation Of Deliverables - Software Design Documents in UML

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#138]
### Issue Description

Week 6's regular meeting covered the first milestone assignment description pdf. We agreed on the sub-titles/sub-tasks that should be included in the milestone report so that they correspond to the ones in the pdf.

* This is a sub-issue of the main issue ["Documenting Milestone Report 1"](https://github.com/bounswe/bounswe2022group2/issues/128).
* The third section of the milestone report has a major headline that reads "Evaluation of Deliverables". Under this primary title, we have established different subtitles, one of which is "Software Design Documents in UML".
* I'll be writing the contents of this section and sharing the written texts as I go along in the comments area of this issue so that you can keep track of my progress.

### Step Details

Steps that will be performed:
- [x] Examining the project description pdf, our requirements, and the other wiki pages relevant to it.
- [x] Filling up the Software Design Documents in UML section with the necessary material.
- [ ] Receiving feedback from @xltvy and make changes to the material if necessary.

### Final Actions

After I have written and shared the texts, @xltvy will go through them. Depending on the review procedure, I will make changes to the material if necessary.

Finally, after all stages have been completed, including the review, I will upload the final version to our milestone report.

### Deadline of the Issue

13.03.2022 - Wednesday - 17:00

### Reviewer

Altay Acar

### Deadline for the Review

14.03.2022 - Thursday - 20:00

**Comment by surmelienes1** [comment]
## Information

I have completed my task of writing the Software Design Documents in UML section, and it is now available for @xltvy to review. I have added this section to our milestone report. If anything changes here or any adjustments are required, I will update the material. You can see the text below:

### **Software Design Documents in UML**

All the team members have collaboratively worked on creating three types of diagrams namely as use-case, class and sequence diagrams, all of which illustrate and summarize the way our program will work, by filling them according to our project requirements as requested by the course instructors. We began by properly studying the details of the UML and considering how the use case diagram, class diagram, and sequence diagram should be constructed. The diagrams were then evaluated in order to properly organize our duties. After the evaluation period, we opted to start designing with the use-case diagram and then go on to the class diagram since these were the inputs to the sequence diagram phase. After completing the use case and class diagrams, we finally created the sequence diagram and double-checked the consistency of all the diagrams to confirm that the integrity goal was met. Then, during problem sessions, we received very helpful comments and feedback from our TA, according to which we later modified the previously created diagrams. Each diagram was generated using the Lucidchart app's capabilities and a series of lengthy meetings including a lot of fruitful discussions and efforts shared by all the team members. Furthermore, at every stage of the UML work, we kept in touch as a group and spoke with one another when needed. Despite the fact that the designs of these diagrams have already been finished, we will maintain them up to date by including any modifications that may arise as the project progresses. On the other side, developing our design has helped us to review and rethink some of the items on our requirements list, and by tweaking the items we addressed, we have come up with a new version of our requirement list that more accurately describes our project than previous versions. Last but not least, since these design diagrams represent the majority of the interactions between external users and relevant software components, they will come in very handy when we begin the coding part of our project.

#### Use-Case Diagram
The use-case diagram graphically illustrates the interaction between the user and the system by visually demonstrating the pathways each designated user type can follow to complete a certain action according to our project requirements. We have identified three type of users: registered and non-registered users, as well as lecture administrators, all of whose various possible pathways may be followed using our use-case diagram. Through utilizing case-specific arrows, our use-case diagram shows the relationships and organization of the functionalities. When looking at our use-case diagram, it is possible for anyone to observe the actions each user type should follow in order to use our application's services.

#### Class Diagram
The class diagram depicts the structure of our project by listing all of our program's classes, attributes, and methods, as well as the links and interactions between them, including a lower-level sketch of the program's functionalities when compared to the use-case and sequence diagrams. The presence of the class diagram will make the coding phase of our project easier and more disciplined in the future.

#### Sequence Diagram
The system will employ its classes and their functions to complete its tasks when it is in operation. We use sequence diagrams to explain how objects interact for a given use case and to highlight the classes and the relationships between them via functions. We utilized arrows to represent the essential steps to initiate use cases as well as what other components or related actors will respond throughout the same use case in a sequential way in these diagrams. Even though sequence diagrams do not cover all conceivable use cases, the 12 distinct sequence diagrams we have designed cover the most important ones. For the sake of consistency, these sequence diagrams are designed in line with the class diagram and the use case diagram.

**Comment by xltvy** [comment]
Thank you for your comprehensive work! I have reviewed it and it is close to perfect. Just a point I would like to mention:
* We may explicitly state relation arrows in three types of diagrams. For example how includes, extends, and includes lecturer arrows work and what they mean.

Other than that, I think it covers everything we had done perfectly.

**Comment by surmelienes1** [comment]
## Information

I have updated the parts in the Software Design Documents in UML section mentioned above by @xltvy. I have added the updated sections to our milestone report. It is now ready to be reviewed by @xltvy. You can see below the parts I have added:

### For the Use-Case Diagram Part:
An «includes» arrow with an open arrowhead from the including(base) use case to the included(common portion) use case shows that the behavior of the included use case is part of the including (base) use case. An «extends» arrow with an open arrowhead pointing from the extension use case to the base use case, as the name implies, extends the base use case and adds more functionality to the system. An «includes»(lecturer) arrow is a special type of the «includes» arrow, which we use to denote that the included use case can only be performed by a lecturer.

### For the Class Diagram Part:
We have utilized 4 case-specific relationship arrows namely Aggregation, Composition, Multiplicity, and Inheritance. When we wished to show that two classes are related but not as closely as in direct association, we used aggregation arrows through which the child class can exist independent of the parent element. Composition associations illustrate connections in which the sub-object only exists as long as the container class does. The multiplicity arrow indicates the maximum number of objects that can participate in a specific relationship or the allowable number of occurrences of an element. Inheritance arrows refer to a class's (child class's) capacity to inherit the same functionality as another class (super class) while also adding additional functionality of its own.

### For the Sequence Diagram Part:
A synchronous message arrow is from left to right solid one in which the sender waits for the recipient to process and return the message before sending another. A dashed return message arrow from right to left indicates that the message receiver has completed processing the message and is handing control back to the message sender. A reflexive message occurs when an item sends a message to itself where the message arrow starts and ends at the same lifeline.

**Comment by xltvy** [comment]
> ## Information
> I have updated the parts in the Software Design Documents in UML section mentioned above by @xltvy. I have added the updated sections to our milestone report. It is now ready to be reviewed by @xltvy. You can see below the parts I have added:
> 
> ### For the Use-Case Diagram Part:
> An «includes» arrow with an open arrowhead from the including(base) use case to the included(common portion) use case shows that the behavior of the included use case is part of the including (base) use case. An «extends» arrow with an open arrowhead pointing from the extension use case to the base use case, as the name implies, extends the base use case and adds more functionality to the system. An «includes»(lecturer) arrow is a special type of the «includes» arrow, which we use to denote that the included use case can only be performed by a lecturer.
> 
> ### For the Class Diagram Part:
> We have utilized 4 case-specific relationship arrows namely Aggregation, Composition, Multiplicity, and Inheritance. When we wished to show that two classes are related but not as closely as in direct association, we used aggregation arrows through which the child class can exist independent of the parent element. Composition associations illustrate connections in which the sub-object only exists as long as the container class does. The multiplicity arrow indicates the maximum number of objects that can participate in a specific relationship or the allowable number of occurrences of an element. Inheritance arrows refer to a class's (child class's) capacity to inherit the same functionality as another class (super class) while also adding additional functionality of its own.
> 
> ### For the Sequence Diagram Part:
> A synchronous message arrow is from left to right solid one in which the sender waits for the recipient to process and return the message before sending another. A dashed return message arrow from right to left indicates that the message receiver has completed processing the message and is handing control back to the message sender. A reflexive message occurs when an item sends a message to itself where the message arrow starts and ends at the same lifeline.

Perfect! I think we can close this issue now and add the texts to appropriate parts of the report. So, I'm closing it now.
