### ISSUE TITLE
Milestone-1: Deliverables - Project Repository

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#139]
### Issue Description

* This is a sub-issue of #128 
* As part of the Milestone Report 1 we need to put deliverables listed in the main issue mentioned above in the report document alongside with an evaluation text for each.
* I took the responsibility of putting **Project Repository** part together with its evaluation to the report.
* **Project Repository** part will depict and summarize the current version of our repository in GitHub and a link to our repository will be available in the document.

### Step Details

Steps that will be performed:
- [x] Examine our project repository
- [x] Write down a summary and evaluation of the project repository
- [x] Add the texts to appropriate parts of the online document
- [x] Provide a link to our project repository

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.

### Deadline of the Issue

14.05.2022 - Thursday - 14.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

14.04.2022 - Thursday - 16.00

**Comment by xltvy** [comment]
## Info:
I have completed the parts related to the **Project Repository** in our _Milestone Report 1_. I have provided texts on our online document and screenshots can be viewed below:

Evaluation of deliverables part:
<img width="625" alt="Ekran Resmi 2022-04-14 12 14 34" src="https://user-images.githubusercontent.com/68481602/163360925-f18497c8-9454-4efd-bf7f-577e27463dc8.png">

Deliverables part:
<img width="629" alt="Ekran Resmi 2022-04-14 12 21 02" src="https://user-images.githubusercontent.com/68481602/163361018-1f391ded-9678-4589-8ab9-d977a3cafcb3.png">

Note: Highlighted number of issues is just an arbitrary number at the moment. Before submission, the total number of issues will be checked and updated.

Now, this issue is ready for a review by @surmelienes1.

**Comment by surmelienes1** [comment]
Thank you very much for your detailed work, great job!

There are two aspects for which some small changes might be needed:

1) **Briefly** mentioning about the issue section of our project repository in the 3.1 section could be better to represent the way we track issues.

2) We now have 38 wiki pages and 141 closed issues, it will be fine as long as you update the numbers in these parts before the milestone report delivery.

Other than these it looks very good, thank you @xltvy for your valuable contributions.

**Comment by xltvy** [comment]
> Thank you very much for your detailed work, great job!
> 
> There are two aspects for which some small changes might be needed:
> 
> 1. **Briefly** mentioning about the issue section of our project repository in the 3.1 section could be better to represent the way we track issues.
> 2. We now have 39 wiki pages and 141 closed issues, it will be fine as long as you update the numbers in these parts before the milestone report delivery.
> 
> Other than these it looks very good, thank you @xltvy for your valuable contributions.

Thank you for the review. Responding both of the points you have mentioned:

1. Yes, I believe we can add some information about issues in 3.1 too. So, I added below text:
    > As the team we have managed and tracked our work using the issue structure in our repository. We regularly opened issues regarding the tasks we carry out, reviewed them, provided suggestions if necessary and closed after finishing the task. Thus, we ensured our repository provides a comprehensive collection of works we have done with details.

2. As I mentioned as a note in the first comment, those numbers will be updated prior to submission. But thanks for extra heads up.

**Comment by surmelienes1** [comment]
It seems very good and complete now, thank you @xltvy for your contributions.

I will now close this issue since I don't have anything to further add, if you have any questions, suggestions, or ideas, you can reopen this issue and add your thoughts as a comment.
