### ISSUE TITLE
Milestone-1: List and Status of Deliverables

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#140]
### Issue Description

Week 6's regular meeting covered the first milestone assignment description pdf. We agreed on the sub-titles/sub-tasks that should be included in the milestone report so that they correspond to the ones in the pdf.

* This is a sub-issue of the main issue ["Documenting Milestone Report 1"](https://github.com/bounswe/bounswe2022group2/issues/128).
* The second section of the milestone report has a major headline that reads "List and Status of Deliverables".
* I'll be writing the contents of this section and sharing the screenshot of the created table as I go along in the comments area of this issue so that you can keep track of my progress.

### Step Details

Steps that will be performed:
- [ ] Examining the project description pdf, our requirements, and the other wiki pages relevant to it.
- [ ] Filling up the table in the List and Status of Deliverables section with the necessary material.
- [ ] Receiving feedback from @xltvy and make changes to the table material if necessary.

### Final Actions

After I have filled the table and shared the screenshot, @xltvy will go through it. Depending on the review procedure, I will make changes to the table material if necessary.

Finally, after all stages have been completed, including the review, I will upload the final version to our milestone report.

### Deadline of the Issue

13.03.2022 - Wednesday - 17:00

### Reviewer

Altay Acar

### Deadline for the Review

14.03.2022 - Thursday - 20:00

**Comment by surmelienes1** [comment]
## Information

I have completed my task of filling the table of List and Status of Deliverables section, and it is now available for @xltvy to review. I have added the created table to our milestone report. If anything changes here or any adjustments are required, I will update the table material. You can see the screenshot below:

### **List and Status of Deliverables**

<img width="1242" alt="Screen Shot 2022-04-14 at 14 20 32" src="https://user-images.githubusercontent.com/74325266/163381316-2e455c78-5018-493e-b469-b849ea34cae6.png">
