### ISSUE TITLE
Milestone-1: Evaluation of Tools

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#141]
### Issue Description

For the [milestone report](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) I will be working on  evaluation of the tools we have used to manage this project. 

This is a sub issue of #128. Details of contents included in the report along with the responsible people can be viewed from the main issue.

### Step Details

Steps that will be performed:
- [x] Evaluation of Discord
- [x] Evaluation of GitHub
- [x] Evaluation of Google Docs
- [x] Evaluation of Figma
- [x] Evaluation of Lucidchart
- [x] Evaluation of  Slack
- [x] General overview of tools used

### Final Actions

After the evaluation of all tools mentioned in the steps are complete and they are added to the milestone report linked in the issue description, they will be reviewed by @mbatuhancelik and with the team when the report is complete.

### Deadline of the Issue

13.03.2022 - Wednesday - 22:00

### Reviewer

Mehmet Batuhan Çelik

### Deadline for the Review

14.03.2022 - Thursday - 20:00

**Comment by ezgy** [comment]
All the parts for evaluation of Tools used have been added to the milestone report. It is now ready for the review @mbatuhancelik

**Comment by mbatuhancelik** [comment]
I reviewed the related part in the milestone report. I have nothing to say about the content, its awesome.
However, there were some grammatical errors which Google Docs was pointing out, sadly I had to be a grammar nazi and execute quick solutions the docs recommended.

**Comment by ezgy** [comment]
> However, there were some grammatical errors which Google Docs was pointing out, sadly I had to be a grammar nazi and execute quick solutions the docs recommended.

I trusted Grammarly would show any errors present but I guess it wasn't enough on its own. Thank you for your help :)
