### ISSUE TITLE
Milestone Report: Requirements

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#142]
### Issue Description

For the [milestone report](https://docs.google.com/document/d/1UD8-7QPV0NNDUppmNQNW438jxSsc8MrYwiKMgWrXKsY/edit) I will be working on the sections concerning requirements.
 

This is a sub issue of #128. Details of contents included in the report along with the responsible people can be viewed from the main issue.

### Step Details

Steps that will be performed:
- [x] Adding glossary to milestone report
- [x] Adding requirements to milestone report
- [x] Evaluation of requirements

### Deadline of the Issue

13.03.2022 - Wednesday - 22:00

### Reviewer

Altay Acar @xltvy 

### Deadline for the Review

13.03.2022 - Wednesday - 22:00

**Comment by xltvy** [comment]
I have reviewed the issue, I think all is fine. Closing #142
