### ISSUE TITLE
Determining System Requirements

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#22]
## Description

As we have learned in the lesson, we should first determine the requirements of the project. It's the initial step before starting to work further. There are different types of requirements and we decided to collect them under distinct titles. Besides, we also decided to assign different people for each type of requirement and a person who is not assigned to that title's issue to review it. We all will read each requirements issue and we are open to commenting further, adding new requirements to those titles even we are not assigned to them.

Our base titles for the requirements, for now, are as follows:
- Functional Requirements
    * User Requirements
    * System Requirements
- Non-Functional Requirements

This structure may be enhanced/enlarged and new base titles can be added in the future. If you have suggestions, please write them as a  comment under this issue.

According to our decision in meeting 2, responsible people for the **system requirements** are:
- [x] @ezgy  - [Searching and Browsing related requirements](https://github.com/bounswe/bounswe2022group2/issues/31)
- [x] @codingAku - [Recommendation related requirements](https://github.com/bounswe/bounswe2022group2/issues/32)
- [x] @surmelienes1  - [Notification related requirements](https://github.com/bounswe/bounswe2022group2/issues/29)

These people will create separate issues for the subsection they work on and link those issues under this main issue with a summary comment. We will manage all system requirement related things here with the help of hyperlinks, comments and so on. 

All comments and reviews about system requirements should be added under this issue. Subsection issues are for individual tracking.

There is one reviewer responsible for this issue and he will review what the assignees have found, what others commented at the end and will make the last sentences before closing the issue to be sure that everything works well.

**Deadline: 13.03.2022 - Sunday - 20:00**
**Reviewer: @bahricanyesil** - Deadline: 14.03.2022 - Monday - 23:59

**Comment by surmelienes1** [comment]
INFO:
I have finalized the **notification related system requirements** for the project. You can review the issue in #29 

All of the details related to these system requirements can be seen in [Requirements Wiki Page](https://github.com/bounswe/bounswe2022group2/wiki/Requirements#12--system-requirements).

**Comment by ezgy** [comment]
I will identify system requirements related to Searching & Browsing. Related issue can be found here:

**Comment by codingAku** [comment]
The discussed requirements about recommendation will be set by me. Related issue for the task is : #32

**Comment by bahricanyesil** [comment]
I have reviewed the requirements of the recommendations @codingAku. Here's my review questions:

1- Recommendations Requirements:

- Will we recommend some courses about hot-topics/trends apart from the personalized recommendations?
- Will we recommend some courses that the friends/followings of the user has taken even though the user has never been interested in them before (since s/he enrolled a day ago for example)?
- Which factors will we be considering apart from the "course interests" of the user? For example: langauge of the course, its rating, reputation of the teacher, enrolled student number and so on.

**Comment by codingAku** [comment]
These topics stated by @bahricanyesil were not yet clarified. The recommendation section will be updated after upcoming meetings.

**Comment by bahricanyesil** [comment]
I have reviewed the requirements of the notifications @surmelienes1. Here's my review questions:

1. What should be our notification frequency that you may predict for now?
2. I am not sure whether you indicated the sentence I will say next in point _1.2.2.8_. If you have, you can ignore this item. We can send a notification for the users who didn't open the app for some time (e.g. 1 week).

**Comment by bahricanyesil** [comment]
I have reviewed the requirements of the searching&browsing @ezgy. I don't have any additional comments or questions.

**Comment by surmelienes1** [comment]
> I have reviewed the requirements of the notifications @surmelienes1. Here's my review questions:
> 
> 1. What should be our notification frequency that you may predict for now?
> 2. I am not sure whether you indicated the sentence I will say next in point _1.2.2.8_. If you have, you can ignore this item. We can send a notification for the users who didn't open the app for some time (e.g. 1 week).

I believe it would be better to shorten the time period to 1 or 2 days so that we can prevent learners from losing the track of their course records. In addition, we can give badges for learners who are in a, let's say, 5 days streak of spending specific amount of time like 15 minutes per day. Badges could change in an encouraging manner as the number of days with a streak increases. I will add the given sentence to the section you have mentioned above.

**Comment by bahricanyesil** [comment]
> 

Thank you!

**Comment by bahricanyesil** [comment]
> > I have reviewed the requirements of the notifications @surmelienes1. Here's my review questions:
> > 
> > 1. What should be our notification frequency that you may predict for now?
> > 2. I am not sure whether you indicated the sentence I will say next in point _1.2.2.8_. If you have, you can ignore this item. We can send a notification for the users who didn't open the app for some time (e.g. 1 week).
> 
> I believe it would be better to shorten the time period to 1 or 2 days so that we can prevent learners from losing the track of their course records. In addition, we can give badges for learners who are in a, let's say, 5 days streak of spending specific amount of time like 15 minutes per day. Badges could change in an encouraging manner as the number of days with a streak increases. I will add the given sentence to the section you have mentioned above.


Thank you!

**Comment by bahricanyesil** [comment]
I guess there is nothing else to comment/answer/change. I am closing the issue since the review process is also completed. You can re-open the issue if you think there is left something. Thank you to those who have contributed to the conversation.
