### ISSUE TITLE
Milestone-2: Providing a Use Case Diagram for Practice App

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#258]
### Issue Description

* As part of the Milestone Report 2 we need to provide related UML diagrams of the practice application under the section of the System Design.
* I took the responsibility of providing **Use Case Diagram** part together.

### Step Details

Steps that will be performed:
- [x] Examine our application's backend and frontend.
- [x] Form the use case diagram using Lucidchart
- [x] Add the diagram to appropriate parts of the online document
- [x] Add the diagram to appropriate page in our wiki

### Final Actions

* After above mentioned steps are done, this issue will be reviewed by the reviewer specified below before finalizing.
* Reviewer will review the issue and give feedbacks/suggestions if necessary.
* After necessary revisions are made, this issue will be closed.

### Deadline of the Issue

20.05.2022 - Friday - 17.00

### Reviewer

Egemen Atik

### Deadline for the Review

20.05.2022 - Friday - 18.00

**Comment by xltvy** [comment]
## Update
I have prepared a use case diagram for our practice application. You can see it in detail via [this link](https://lucid.app/lucidchart/68b26fc2-9485-4267-ad6d-2fd6d191f29f/edit?invitationId=inv_55e82448-d29e-4d7e-b309-aba3f3e1e8e9). I am also providing a screenshot of it. After a review by @egemenatikk we can add it to the related part in our document and to its wiki page.
![Practice-App Use Case Diagram](https://user-images.githubusercontent.com/68481602/169539442-b5e641ef-16fd-45ec-9ee9-876da50015ca.jpeg)

**Comment by onurkomurcu** [comment]
I have reviewed your work, @xltvy. Great job!
