### ISSUE TITLE
Milestone-2: Documenting Class Diagram

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#285]
### Issue Description

* As part of the [Milestone Report 2](https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit?usp=sharing) we need to provide the deliverables we used.
* I and @hasancan-code  took the responsibility for the first part of this evaluation section. The parts that we  will evaluate are written in the step details section below.

### Step Details

Steps that will be performed:
- [x] Rating class - @codingAku 
- [x] Category class - @codingAku 
- [x] Lesson Class - @codingAku 
- [x] Event class - @hasancan-code 
- [x] User class - @hasancan-code 

### Final Actions

After review, class diagram will be ready to put in documentation.

### Deadline of the Issue

20.05.2022 - Friday 17.00

### Reviewer

Bahrican Yesil

### Deadline for the Review

20.05.2022 - Friday 23.00

**Comment by codingAku** [comment]
UPDATE: I am working on RatingClass diagram for practice-app can be reached from this [link](https://lucid.app/lucidchart/9997bd8d-3449-413c-81b5-c999a48f3c49/edit?invitationId=inv_5f75ddb6-6d2a-46fc-88ea-a224ee2bec08).

**Comment by codingAku** [comment]
UPDATE: Final version of class diagram is down below:
![image](https://user-images.githubusercontent.com/64018144/169564739-b74fd5ce-6b96-4c5d-b14f-d4d8b98018f9.png)
You can reach from [link](https://lucid.app/lucidchart/9997bd8d-3449-413c-81b5-c999a48f3c49/edit?beaconFlowId=84733D7C8B3CFE9A&invitationId=inv_5f75ddb6-6d2a-46fc-88ea-a224ee2bec08&page=0_0#) also.

**Comment by bahricanyesil** [comment]
It is good enough for our practice app. Good work @codingAku and @hasancan-code. I don't have anything more to add/change.

**Comment by onurkomurcu** [comment]
Closed.
