### ISSUE TITLE
Milestone-2: Providing a Sequence Diagram for Practice App

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#296]
### Issue Description

* As part of the Milestone Report 2 we need to provide related UML diagrams of the practice application under the section of the System Design.
* I took the responsibility of providing 5 Sequence Diagram.
* It can be viewed from this [link](https://lucid.app/lucidchart/f697491d-de25-4b00-ba7e-a456551e7547/edit?invitationId=inv_06d40aaa-ab07-4a93-97b1-e76e1f55379b).

### Step Details

Steps that will be performed:
- [x] Examine our application's backend.
- [x] Create sequence diagrams using Lucidchart
- [x] Add the diagram to appropriate parts of the online document
- [x] Add the diagram to appropriate page in our wiki

### Deadline of the Issue

20.05.2022 - Friday - 23.00

### Reviewer

Egemen Atik

### Deadline for the Review

20.05.2022 - Friday - 23.59

**Comment by onurkomurcu** [comment]
I have finalized my work. It can be seen from below and through the link provided in the issue description. It is ready to be reviewed by our team members.
![Project Plan Sequence Diagrams](https://user-images.githubusercontent.com/92719802/169584401-95daf285-10b8-4236-9be0-b9402d263154.jpeg)

**Comment by onurkomurcu** [comment]
Closed.
