### ISSUE TITLE
Milestone-2: Evaluation of Processes

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#304]
### Issue Description

For the Milestone Report 2 I was assigned to alter the sections regarding the evaluation of processes. The information will be added directly to the milestone report on google docs (link: https://docs.google.com/document/d/1g54mQYJxYoSeIKYAIz8FMHkJQ0-yczkttu_ddg0-PPs/edit) and can be viewed there. 

### Step Details

Steps that will be performed:
- [x] Evaluation of Team meetings
- [x] Evaluation of TA meetings 
- [x] Evaluation of Issue Creation and Management
- [x] Evaluation of Pull Request Creation and Management

### Final Actions

Sections will be added to the shared document right away. Improvement suggestions will be added using comments functionality of google docs.

### Deadline of the Issue

20.05.2022

### Deadline for the Review

20.05.2022

**Comment by ezgy** [comment]
Parts 3.2.1- 3.2.4 have been added to the document and can be viewed by the team.
