### ISSUE TITLE
Update the Project plan for upcoming semester

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#316]
### Issue Description

The project plan from our last semester is too outdated!  Thus, we need to come up with a better one.

Under this issue, we shall create a plan for the semester, with emphasis on our actions up to first milestone.

As previously discussed, we want to be done with login and profile page requirements that are not related to achievements, and embark on the courses page until the first milestone comes.

 

### Step Details

Steps that will be performed:
- [x] Determine which requirements will be satisfied.
- [x] Order those requirements and propose a plan.
- [x] Discuss the proposed plan with all members.

### Final Actions

Upon completion, plan shall be visible on our wiki page!

### Deadline of the Issue

10.10.2022 Monday 23:59

### Reviewer

Gökay Yıldız

### Deadline for the Review

11.10.2022 Tuesday 12:00

**Comment by mbatuhancelik** [comment]
Since working with the application we used for the last semester, I believe prototyping the plan on Notion would be more beneficial. 
Under this link you can see the last form of the proposal me and Onur created. 

https://www.notion.so/a65c56f90ecb4d3fb318935283751e05?v=846337c07136445b9c1bae89766b6cb2

Since we are not aware of the future tasks, currently some tasks are in form of vague representations. As they are completed  and divided into tasks that are assigned to people, this plan can be updated.

**Comment by mbatuhancelik** [comment]
Since working with the application we used for the last semester, I believe prototyping the plan on Notion would be more beneficial.
Under this link you can see the last form of the proposal me and Onur created.

https://www.notion.so/a65c56f90ecb4d3fb318935283751e05?v=846337c07136445b9c1bae89766b6cb2

Since we are not aware of the future tasks, currently some tasks are in form of vague representations. As they are completed and divided into tasks that are assigned to people, this plan can be updated.

**Comment by xltvy** [comment]
Thank you @mbatuhancelik and @onurkomurcu for the effort. I think using Notion for project plan is a brilliant idea. I have reviewed your proposal and have some suggestions about it:
1. I think updating requirements page may take longer. Because after reviewing it and reading all other member's suggestions regarding the requirements, we may be changing a lot.
2. Profile page is one of the most complex pages of the application. So, it may take a bit longer time than 5 days. We may decide sub parts of the profile page to implement during this time period of project plan, or make its timespan more than 5 days. When we start developing the profile page we can give further detailed plan about which parts will be worked on in which days etc.

**Comment by mbatuhancelik** [comment]
> I think updating requirements page may take longer. Because after reviewing it and reading all other member's suggestions regarding the requirements, we may be changing a lot.

After checking #323 I think you are right, I made the adjustment so that next week, we will be focusing on revisions.

> We may decide sub parts of the profile page to implement during this time period of project plan, or make its timespan more than 5 days.

I added course page implementation to add as a buffer zone, we can use that time to focus on profile page more. However, profile page has dependencies on annotations, classes, etc so I believe implementing those after their requirements are satisfied will be more beneficial. I believe for now we can focus on base profile page and extend it in future.

**Comment by bahricanyesil** [comment]
@mbatuhancelik and @onurkomurcu, thank you for your efforts. I also agree with Altay that using Notion with its timeline feature is a nice idea.

I revised your work and have some suggestions:
1. If I see correctly, the milestone 1 is set to 20 November. However, in the lecture slides there was an info that milestone 1 will be on 1 November or something like that. So we should revise the project plan in the PS and may bring forward some of the items to include in the first milestone. 
2. We can change "determining team members" to "determining sub-team members" if you want to indicate the mobile/front/back teams.
3. We can put update requirements/mockups/diagrams items one week earlier (deadlin to 18 October) because we have already revised most of them and what we need to do is update and decide on the final version of the initial updated requirements of this term.
4. When we perform the above step then everything will be moved one week earlier and so that we will be finished course feature in November 5. However since we should finish the deployment related things and prepare the milestone report before the first deadline. We may not be able to get ready the course feature until the first milestone and only have signup, login and profile screens/features. We can discuss this in the PS section.
5. I'm not sure whether we can have a holiday (buffer zone), so re-adjusting works and having a conversation about the items&deadlines seem necessary as the whole team.

**Comment by mbatuhancelik** [comment]
Me and @bahricanyesil talked with @uskudarli about optimal action path for the first milestone. I will deliver more details in our lab meeting but TLDR: we are expected to set an environment that works on everyone and on AWS and perform minimal database reading operations using them, so the important point is setting up the environment and its proof of work.

On another note, navigating from the last year I assumed that the first milestone would be around 20th of November, however, to my surprise it was actually 1st of November. 

Required updates are now made to the project plan now, which is subject to change about our lab meeting in 11th of October.

**Comment by onurkomurcu** [comment]
Project plan is discussed during the lab session with team members and TA. From now on, last version of the project plan can be seen below. If there is any update and addition, last version of the project plan can be seen from [Project Plan page](https://github.com/bounswe/bounswe2022group2/wiki/Project-Plan). Thank you all for your contribution!
![Screen Shot 2022-10-13 at 23 08 39](https://user-images.githubusercontent.com/92719802/195701334-34ed4efc-26cf-42a9-8147-4897cc6fa0e2.png)
