### ISSUE TITLE
Preparing Milestone 1 - CMPE 451 Deliverables

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#409]
### Issue Description

As it is stated in the Customer Milestone 1 Deliverables instructions, I will create another folder named "CMPE451_Customer_Presentation_Milestone_1" under the "deliverables" folder. I will add the hyperlinks of the mentioned documents in the deliverables MD file.

Other than this, each individual will write his/her contributions under the "Individual Contributions Report" title in the given format.

### Step Details

Steps that will be performed:
- [x] Create the "CMPE451_Customer_Presentation_Milestone_1" folder
- [x] Create the "deliverables.MD" file
Add hyperlinks for
- [x] Software Requirements Specification
- [x] Software Design (UML)
- [x] Scenarios and Mockups
- [x] Project Plan
- [x] All individuals added his/her reports

### Final Actions

All these processes will be conducted in another branch. After the branch is approved by at least 1 person, it will be merged with the dev.

### Responsible People

- [x] Bahrican Yesil
- [x] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [x] Onur Kömürcü
- [x] Mehmet Batuhan Çelik
- [x] Hasan Can Erol
- [x] Ecenur Sezer
- [x] Koray Tekin
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

31.10.2022 - Monday - 17:59

### Reviewer

Altay Acar

### Deadline for the Review

31.10.2022 - Monday - 23:59

### Final To-Dos

- [x] Every responsible shared an info about the sections/parts s/he will perform.
- [x] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [x] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by bahricanyesil** [comment]
I added my individual to the "deliverables.md" file under the folder "CMPE451_Customer_Presentation_Milestone_1". You can see my report [here](https://github.com/bounswe/bounswe2022group2/blob/milestone1-deliverables-409/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member).

**Comment by codingAku** [comment]
My individual report to deliverables.md can be accessed [here](https://github.com/bounswe/bounswe2022group2/blob/dev/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member-1)

**Comment by bahricanyesil** [comment]
@codingAku and all team members, please order according to the surnames.

<img width="981" alt="Screen Shot 2022-10-29 at 14 37 46" src="https://user-images.githubusercontent.com/60237280/198829308-4fca019a-9204-43d6-9ddb-843e6907c9f5.png">

**Comment by codingAku** [comment]
> @codingAku and all team members, please order according to the surnames.
> 
> <img alt="Screen Shot 2022-10-29 at 14 37 46" width="981" src="https://user-images.githubusercontent.com/60237280/198829308-4fca019a-9204-43d6-9ddb-843e6907c9f5.png">

Updated.

**Comment by bahricanyesil** [comment]
> > @codingAku and all team members, please order according to the surnames.
> > 
> > <img alt="Screen Shot 2022-10-29 at 14 37 46" width="981" src="https://user-images.githubusercontent.com/60237280/198829308-4fca019a-9204-43d6-9ddb-843e6907c9f5.png">
> 
> Updated. Although I get Page Not Found on your link. @bahricanyesil 

Fixed the link, thank you @codingAku

**Comment by ezgy** [comment]
I have added my individual contributions to the report.

**Comment by hasancan-code** [comment]
I have added my individual contributions to the report.

**Comment by surmelienes1** [comment]
## Update

I have added my individual report to the deliverables file for the first milestone. 

You can access my individual report from [here](https://github.com/bounswe/bounswe2022group2/blob/dev/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member-5).

**Comment by egemenatikk** [comment]
I added my individual contributions to our group report. It can be seen from [here](https://github.com/bounswe/bounswe2022group2/blob/dev/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member-1).

**Comment by onurkomurcu** [comment]
I have also added my individual contributions to the [group report](https://github.com/bounswe/bounswe2022group2/blob/dev/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member-1).

**Comment by Koraytkn** [comment]
I have added my individual contributions to the [group report](https://github.com/bounswe/bounswe2022group2/blob/dev/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md#member-1).
