### ISSUE TITLE
Milestone 1: Project Plan

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#448]
### Issue Description

As we discussed in [Meeting #4](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%234-for-CMPE-451-(25.10.2022)) project plan should be transferred to ProjectLibre. I will transfer whole project plan. Addition to that, plan will extended to the last day of the semester. For this part of the task, I will be working with @mbatuhancelik . 

### Step Details

Steps that will be performed:
- [ ] New project plan will be initialized
- [ ] Whole project plan will be transferred to ProjectLibre
- [ ] Project plan wiki page will be updated
- [ ] Previous and last version of the project plan will be posted here 

### Final Actions

When the whole work is done, it can be reviewed from here.

### Deadline of the Issue

31.10.2022 - Monday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

01.10.2022 - Tuesday - 15.00

**Comment by mbatuhancelik** [comment]
I created a meta plan and linked it to our members: 
https://www.notion.so/a65c56f90ecb4d3fb318935283751e05?v=846337c07136445b9c1bae89766b6cb2
After taking their opinions and making the necessary changes, we can migrate this plan to libre.

**Comment by onurkomurcu** [comment]
I have transferred the last version of the project plan to projectlibre. Final result can be seen below.
[CmpE451_ProjectPlan_Milestone1.pdf](https://github.com/bounswe/bounswe2022group2/files/9904128/CmpE451_ProjectPlan_Milestone1.pdf)

**Comment by xltvy** [comment]
Well done, we can update the wiki pages, deliverables accordingly and then close the issue.

**Comment by onurkomurcu** [comment]
It is uploaded to the [Project Plan wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Project-Plan).  We also provided hyperlink in the deliverables for the project plan. This issue can be closed now.
