### ISSUE TITLE
Milestone 1: Mobile - Evaluation of Tools and Processes

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#475]
### Issue Description

For the group review part of the Milestone 1 report, we should write the evaluation of tools and processes. We decided to complete this part as 3 people from each sub-team. Since I am a part of the mobile team, I will write the evaluation of tools and processes used in the development.

### Step Details

Steps that will be performed:
- [x] Copy the previously used tools with their evaluation from the last term
- [x] List the tools and processes used
- [x] Write evaluation for each of the tools and processes listed
- [x] Add the evaluations to the report

### Final Actions

Once the evaluation process is finished, I will get the review from the reviewer and then add the written texts to the report.

### Deadline of the Issue

03.11.2022 - Thursday [23:59]

### Reviewer

Egemen Atik - @egemenatikk 

### Deadline for the Review

04.11.2022 - Friday [15:00]

**Comment by bahricanyesil** [comment]
## Evaluation of Tools

We used so many different tools while we are developing the project. Since in this term we have divided into different sub-teams, the number, and variety of the tools we used also increased. When we are having a conversation about choosing a tool for development, we considered several points. We can say that one of the most significant items that we considered is that the tool has to enable us to work collaboratively and to track each other easily in an organized way. Another thing we considered is the use of the tool. The reason behind this consideration is the fact that we have so limited time to develop the project. Therefore, having familiarity with the tool will be a good advantage for all of us.

**Comment by bahricanyesil** [comment]
## Discord

We used Discord as our main communication tool. All team meetings including the sub-team meetings were held via the voice channels we created. We have created a different voice and text channels for different needs such as meeting notes, mobile team, front-team, back-team, research material, and general and random chats. We found Discord to be useful as our main communication tool since it is easy to use and many of us were already familiar with it. Having multiple voice channels in the same group and being able to separate text channels were the main features that we benefit from. 

Besides these, using threads to separate messages within the same text channel (such as having a new thread for each meeting or research topic) made our channel easy to navigate and organized. Overall, Discord provided all the basic features we required from a team communication environment. All team members were able to organize, see and track the notes, and texts written under the channels.

**Comment by bahricanyesil** [comment]
## GitHub

The GitHub repository is where all progress made as well as all the deliverables can be viewed. Our whole code is stored under GitHub and we are managing our code base with the help of Git&GitHub. Our repository provides a portfolio of all the work we have done. It includes information about who we are and all the design and research we have done in the wiki section. It includes information about what should be expected from the project we are developing and also who has done what via the regularly created and maintained issues. Additionally, since we started the real-implementation of the real project we assigned (Online Learning Platform), the whole code of the project is in the project repository.

GitHub is the most important tool we are using during the development of the project. The reason for this is the fact that it gathers everything we have done in one place including not only the code lines but also the documents, deliverables, meeting notes, and so on. Almost all types of work we have done include Github in one way, every task of design, documentation, research, assignment tracking, and even reviews include and can be reached from our GitHub repository. 

We are also actively using the version control aspects of Github such as committing changes and merging branches. We actively opened issues for the work we will do, we held the development processes under branches we created. We opened pull requests after each development, got a review (at least 1 with the help of branch protection we set), and merged firstly to dev and then master. 

We found Github to be useful for this purpose as it contains every feature we needed for such a tracking and management system. Also, it has good user interaction for both the contributors and outsiders observing. Alternatives such as BitBucket provide similar features for version management but we find Github is more useful in terms of merging version control and information wiki together in one space.

**Comment by bahricanyesil** [comment]
## Flutter

We conducted research on Flutter before we decided to use it for mobile development. Here are our findings and reasonings to choose Flutter as the tool for Mobile development:

1- Flutter is based on Dart language which is so similar to Java. Since we all took beginner-level courses in the department with Java and learned the programming basics with Java, using Dart will not be a problem for us, and the adaptation process will be easy for us.
2- In Flutter, the visual (UI) and logic parts of the code are included in the one-single code base. This fact eases and speeds up the coding. In the end, we can reach MVP and the aimed version of the app in a shorter time compared to other technologies.
3- Normally, it is expected to performance decrease in cross-platform technologies. Even though Flutter has also some downgrades, it serves near-to-native performance in most cases with the help of the Dart compiler since it converts the Flutter app to native code. In the end, we are able to use the native features.
4- We are building a huge app with lots of features and so with lots of screens, UI components, widgets, and so on. This brings up complexity and difficulty of implementation. However, Flutter gives various UI components as in-built support and you can use all of them as just widgets. Besides this, its package system ([pub.dev](https://pub.dev/)) has lots of free open-source packages that include various design/logic solutions for apps.
5- Flutter has a hot-reload feature with a very fast reloading time. This feature will be very useful in the development and debugging process!
6- We have experienced people with Flutter, this will speed up our development and we will be able to implement almost all features with good design and code patterns in the given time (1 semester).
7- We have people who are very curious about Flutter and want to learn it. This curiosity and desire to learn will carry us forward when we start to code the project.

After the first milestone demo, we understood that we gave the correct decision by choosing Flutter. We were able to quickly develop the first milestone with lots of good features, nice design touches and less problems.

**Comment by bahricanyesil** [comment]
I filled in the parts that I was responsible for in the "Evaluation of Tools&Processes" section. I've created our "group_review.md" file and the corresponding sections mentioned in the milestone description. You can view the file under "deliverables" folder in our project repository.

**Comment by bahricanyesil** [comment]
I've created a [PR](https://github.com/bounswe/bounswe2022group2/pull/484) which contains required changes in this issue. This issue will be closed with the merge of that PR.
