### ISSUE TITLE
Milestone 1: Reviewing Our First Milestone: Against Objectives and Customer Presentation Parts

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#481]
### Issue Description

For our group report of Milestone-1, we should prepare a general review of our group's work. In our fourth group meeting, 3 members are assigned to complete this task and I am one of them. I will contribute to this general review by writing "against objectives" and "the customer presentation" parts.

### Step Details

Steps that will be performed:
- [x] Revise our group objectives until the first milestone
- [x] Compare what we expect to achieve and what we actually achieve
- [x] Write review about demo presentation with the help of notes taken during our demo session
- [ ] Add those parts to our first milestone group report

### Final Actions

After I complete my tasks and getting my reviewer's approval, I am going to add my part to general review report and then we will add the general review report to our first milestone group report.

### Deadline of the Issue

03.11.2022 - Thursday - 23:59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

04.11.2022 - Friday - 15:00

**Comment by egemenatikk** [comment]
## Against Objectives Part

We held our first meeting of this semester at 4th October 2022 and we presented our progress, demo presentation at 1st November 2022, first. Between these two dates we set some objectives to ourselves, they can be seen from our project plan in detail. During this period, we firstly welcomed our new members and updated our wiki pages accordingly. Then, we decided to create our project plan until Milestone-1. After that, we revised the diagrams, mock-ups and requirements we prepared last semester and updated necessary parts according to our customer's requests and suggestions. Later, we determined sub-teams, their members, technologies they will use and started to work on implementation of our project. We decided on our application's name, logo, font type and theme(color schema). We decided to prepare sign-up screen, login screen, forget password screen and verification screen for our first demo presentation, primarily. To do that we decided on endpoints, their request models and response models. Then, front-end and mobile teams started to prepare designs for the pages mentioned above and after necessary endpoints are implemented by our back-end team, front-end and mobile teams provided back-end connection to their screens. We successfully dockerized and deployed our back-end and front-end and released the APK of our mobile application. We reached our primary objectives for a fair amount of time before our first demo presentation, so we decided to add some additional screens and features to our application, even if they are mainly static. So, we add a mock-up home page screen and a static profile page screen as front-end and mobile teams with the help of endpoints implemented by our back-end team. Before our demo presentation, we prepared two scenarios and several personas to enrich our presentation's story-telling property and we prepared our milestone-1 report.  Now, we are planning our second milestone. In summary, we achieved everything we planned to achieve and some extra functionalities, we proceed step by step according to our project plan and completed the tasks we determined at the early stages of this semester. In terms of meeting our objectives, we think we did a pretty good job.

**Comment by egemenatikk** [comment]
## The Customer Presentation Part

We tried to give an interactive, intriguing demo presentation to all viewers and, especially, our customers. For that purpose, we developed two scenarios and a number of personas. In this scenarios, we paid attention to emphasize all features we implemented. We were also careful about our time management and practiced the presentation a few times before the demo session day, we also set a timer for our presentators to follow during the demo. Since we successfully deployed our back-end, front-end and released the APK of our mobile app, we did not have hard time while telling our scenarios and presenting our application. We tried not to stay quiet as much as we can but for a small number of times we failed to do so, for example we could have continued our story-telling while our presentators are using the application. Before our demo session, we thought about changing the term "courses" to "learning spaces", but doing so would require us to change some of our requirements and diagrams, so we decided to postpone doing so to our second milestone. Our customers gave us feedbacks about our main page structure, notifications flood and gave credit to us for providing different experiences in our website and mobile application. We also received very nice comments and positive feedbacks from our classmates. One important thing we noticed as a team is that verification functionality was only present in our application.

**Comment by egemenatikk** [comment]
My task is completed, it can be updated according to comments and suggestions from the reviewer. This issue is now ready to be reviewed by @surmelienes1.

**Comment by egemenatikk** [comment]
@xltvy opened a general issue to track progress in general review of milestone-1 task, that issue can be viewed from #482. This issue is a sub-issue of #482.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @egemenatikk for your valuable contributions! The two parts you wrote above are really well articulated and structured from my point of view.

Since I have nothing else to say at this time, I will now close this issue. You can reopen this issue and add your comments if you have any new questions or recommendations.
