### ISSUE TITLE
Milestone 1: Review the Milestone

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#482]
### Issue Description

With the first customer presentation coming to an end, we have developed, deployed, and released the 0.1.0-alpha of our application, Learnify. As part of the **Milestone Group Review** part of the Milestone 1, we have planned to provide the **Review the Milestone** part as a collaborative work of three people: @xltvy, @egemenatikk, @surmelienes1 

This issue is the main issue of the Review the Milestone part. Each responsible member will open their own sub-issues regarding the parts, they will work on and then link their sub-issues under this issue.

The Milestone 1 can be reached from [here](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md).

### Step Details

Steps that will be performed:
- [x] Every responsible member will create their sub-issues.
- [x] Every responsible will complete their parts.
- [x] All material will be added to the [report](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md).

### Final Actions

After every sub-issue is resolved and our material is added to the milestone report, this issue will be closed.

### Responsible People

- [X] Egemen Atik - #481 
- [X] Altay Acar - #489 
- [X] Muhammed Enes Sürmeli - #492 

### Deadline of the Issue

03.11.2022 - Thursday - 23.59

### Reviewer

Egemen Atik

### Deadline for the Review

04.11.2022 - Friday - 16.00

**Comment by egemenatikk** [comment]
I opened my issue and completed my task, it can be viewed from #481.

**Comment by xltvy** [comment]
> I opened my issue and completed my task, it can be viewed from #481.

Can you link your issue to this issue description right next to your name, and also mention this issue in your issue.

**Comment by xltvy** [comment]
I have updated the [group review](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md) for the **Review the Milestone** section. You can see the changes from here #503. After the changes are merged, we can fill the relevant sections and close this issue.

**Comment by surmelienes1** [comment]
## Update

I have updated the [group review](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md) for the Review the Milestone section by adding the what went well and what did not go well parts to the Milestone-1 report. You can see the changes from here #508. After the changes are approved and merged, we can close this issue.

**Comment by egemenatikk** [comment]
I updated [general group review](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md) with the additions I made in issue #481 and merged it to the master branch. Now, all necessary tasks are done, we can close this issue after a final review.

**Comment by xltvy** [comment]
Thank you all for your effort, closing this issue.
