### ISSUE TITLE
Milestone 1: Filling Individual Works and Responsibilities Parts of Group Review

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#483]
### Issue Description

In our group review for milestone-1, list of work done by each member should be placed. Every team member should fill the responsibilities and individual work section of their own in the file named "group_review.md" opened by @bahricanyesil under "deliverables" folder.

### Responsible People

- [x] Altay Acar
- [x] Egemen Atik
- [x] Ezgi Aysel Batı
- [x] Mehmet Batuhan Çelik
- [x] Hasan Can Erol
- [x] Onur Kömürcü
- [x] Ecenur Sezer
- [x] Muhammed Enes Sürmeli
- [x] Koray Tekin
- [x] Bahrican Yeşil
- [x] Mehmet Gökay Yıldız

### Final Actions

After all members complete their parts, the table will be added to general group review report.

### Deadline of the Issue

03.11.2022 - Thursday - 23:59

### Reviewer

Bahrican Yesil

### Deadline for the Review

04.11.2022 - Friday - 15:00

**Comment by bahricanyesil** [comment]
I've filled my corresponding parts in both the "Responsibilities" and "Summary of Individual Work" sections in the group review file. You can see them under the deliverables folder - milestone 1 - group review file.

Here are the corresponding screenshots:
<img width="812" alt="Screen Shot 2022-11-03 at 16 36 32" src="https://user-images.githubusercontent.com/60237280/199735131-f741a499-709d-4908-a5a1-13f3930338b9.png">

<img width="774" alt="Screen Shot 2022-11-03 at 16 36 39" src="https://user-images.githubusercontent.com/60237280/199735163-2c377912-935a-48e3-8a18-5253a99582f1.png">

<img width="735" alt="Screen Shot 2022-11-03 at 16 37 26" src="https://user-images.githubusercontent.com/60237280/199735356-ff8f3f70-6906-4859-8bb9-e54fb95e4b87.png">

**Comment by ezgy** [comment]
I've filled my individual responsibilities part on the [Group Review](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md). My added parts can be seen on pr #486

**Comment by egemenatikk** [comment]
I have filled my individual responsibilities, personal efforts part on our [Group Review for Milestone-1](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md). Related changes can be viewed from PR #490.

**Comment by onurkomurcu** [comment]
## The Work I Done:

- **Onur Kömürcü**
     1. Implementing login screen and its backend connection for mobile app.
     2. Implementing widget and network test for login screen.
     3. Reviewing the codes that are written by mobile team.
     4. Learning implementation details of Flutter.
     5. Revising achievements related software requirements specifications and UML diagrams.
     6. Updating project plan and communication plan.
   
***

- **Onur Kömürcü:**
   |Issue Title|Link|
   |-----|:--------:|
   |Mobile: Setting up development Environment|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/372)|
   |Mobile: Implementation of Login Screen Including Backend Connection|[Issue Link](https://github.com/bounswe/bounswe2022group2/pull/398)|
   |Mobile: Writing Tests for Login Page|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/447)|
   |Milestone 1: Project Plan|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/448)|
   |Updating Communication Plan|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/377)|
   |Updating the Project plan for upcoming semeste|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/316)|
   |Revising the Requirements: Achievements and Badges|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/333)|
   |Revising the Diagrams based on Achievements|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/346)|
   |Updating Personal Wiki Pages|[Issue Link](https://github.com/bounswe/bounswe2022group2/issues/324)|

   |Pull Request Title|Link|
   |-----|:--------:|
   |Mobile: Implementing Login Page Including Backend Connection|[#396](https://github.com/bounswe/bounswe2022group2/issues/396)|
   |Mobile: Tests for Login Page|[#485](https://github.com/bounswe/bounswe2022group2/pull/485)|

**Comment by codingAku** [comment]
My individual report is complete. PR is #500.

Summary:

   1. Implementing the login endpoint
    2. Implementing the verify email endpoint
    3. Testing and documenting both endpoints
    4. Implementing unit tests for both endpoints
    5. Reviewing all works done by backend teammates  
    6. Doing research on technologies needed to use on backend development
![imza kaşe](https://user-images.githubusercontent.com/64018144/199858391-fc756371-f4d3-4938-802d-6b65780c8c3b.png)

**Comment by xltvy** [comment]
I have completed my individual report and can be seen below:
### Responsibilities
<img width="968" alt="Ekran Resmi 2022-11-04 12 52 36" src="https://user-images.githubusercontent.com/68481602/199944444-2259cd91-b939-443e-b7f2-e3b2d455beb7.png">
### Issues and PRs
<img width="826" alt="Ekran Resmi 2022-11-04 12 52 45" src="https://user-images.githubusercontent.com/68481602/199944539-707d2247-c1c9-4387-a550-40aa6ab82227.png">

**Comment by surmelienes1** [comment]
## Update

I have added my individiual contributions to the project in terms of the responsibilities, issues and pull requests which you can see below and in [this pull request](#508):

### Responsibilities
<img width="591" alt="Screenshot 2022-11-04 at 15 58 10" src="https://user-images.githubusercontent.com/74325266/199978051-1fba8bc4-70e9-491a-92ce-b11f55b63e2d.png">


### Issues and Pull Requests
<img width="616" alt="Screenshot 2022-11-04 at 15 57 59" src="https://user-images.githubusercontent.com/74325266/199978063-c1fb6ecb-6b6d-4503-8579-b52fd40db468.png">

**Comment by hasancan-code** [comment]
My individuals are added. It can be seen from [#PR511](https://github.com/bounswe/bounswe2022group2/pull/511). After the pr validation is confirmed it can be merged.

**Comment by egemenatikk** [comment]
All members have added their individual efforts to the necessary part in general group review for Milestone-1, so this issue can be closed now.
