### ISSUE TITLE
Milestone 1: Reviewing the Milestone - Progress

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#489]
### Issue Description

As part of the milestone review in our Milestone Report 1, I will be completing the progress part. For that extent, Our progress from the start of the semester, what we have achieved and how we have accomplished our goals will be outlined.

This issue is a sub-issue of #482. Thus, it will be linked to and can be tracked from the main issue as well.

### Step Details

Steps that will be performed:
- [x] Provide a general description of our progress thus far
- [x] Provide what we have achieved and how
- [x] Provide the final text as a comment under this issue

### Final Actions

After I complete the tasks and provide the progress text, I will update the milestone report upon review accordingly.

### Deadline of the Issue

03.11.2022 - Thursday - 23.59

### Reviewer

Egemen Atik

### Deadline for the Review

04.11.2022 - Friday - 16.00

**Comment by xltvy** [comment]
## Update
Progress text can be seen below. Now it is ready for a review.
***
With the start of the semester, we have started the development of our application Learnify. Learnify is an online learning platform, which aims to create a collaborative learning space for all the users. Although we have successfully completed the design and planning phases of our project last semester, we needed to revise most of the design before starting the development. We have divided into three teams, which have worked on separate parts of our application. Frontend team worked on the web application, mobile team worked on the mobile application, and the backend team worked on the development of our RESTful API. At the beginning of our development phase we have updated our communication plan and project plan according to the needs and aims of the scope of our project. We have welcomed new members. Every week we have held a customer meeting, in which we discussed the current state of our project and in the following a general group meeting where everyone participated and the tasks are identified for the next week. Every development team also held their own meetings each week to meet the objectives of our application’s development.

For the milestone 1, we have aimed to have a fully functioning authentication part of our application. After discussing with our customer, we have decided to have e-mail verification for a registered user. Also, when a user forgets their password, they can also reset their password via e-mail verification. For the demonstration purposes, a static mockup homepage also can be seen after successfully signing in to our application. To develop every related part of the project each team collaboratively worked together and before Milestone 1 every feature, page, and screen was implemented, tested, dockerized, and deployed as planned. We have effectively used React and some external libraries for frontend, Flutter for mobile, Node.js for the backend, Docker for dockerization, and AWS for the deployment.

**Comment by egemenatikk** [comment]
Thank you for your work, @xltvy. I could not come up with a thing to add to or change in your writing. Therefore, this issue is completed and I am closing it.
