### ISSUE TITLE
Milestone 1: Reviewing the Milestone - What Went Well and What Did Not Go Well Parts

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#492]
### Issue Description

I will complete the what went well and what did not go well parts of the milestone review in our Milestone Report 1. In accordance with the project's scope, I will create a two-part statement that lists the things we did well and where we could have done better from the start of the project until the day the milestone was presented.

This issue is a part of issue #482. As a result, it will be connected to and traceable from the root issue.

### Step Details

Steps that will be performed:
- [x] Identify the areas where we excelled and where we could have done better overall.
- [x] Describe how we arrived at these results.
- [x] Submit the completed content as a comment to this issue.
- [ ] Include these parts to our first milestone group report.

### Final Actions

l will include my results to the general review report once I have finished my tasks and received my reviewer's permission, and then we will integrate the general review report into our first milestone group report.

### Deadline of the Issue

04.11.2022 - Friday - 15.00

### Reviewer

Altay Acar

### Deadline for the Review

04.11.2022 - Friday - 17.00

**Comment by surmelienes1** [comment]
## Awaiting Review

I have completed the parts for which I was responsible as you can see below; they may be amended in response to the reviewer's comments and recommendations. The reviewer, @xltvy, can now evaluate the results.

### What Went Well Part

There are some areas where we, as a team, have been quite successful in dealing with the challenges we faced from the beginning of the term to the milestone delivery. First of all, since everyone on the team, including our newly joined teammates, worked diligently and in accordance with the project plan throughout the entire development process, and completed the tasks assigned to them in a timely and thorough manner, all the components we implemented worked perfectly during the milestone presentation. Secondly, we were also able to provide the deliverables asked by the instructors before the deadline they set to us as a natural result of the fact that all members of the group were able to finish their job on time. Moreover, despite the fact that we had to be divided into 3 separate groups at the beginning of the semester according to the needs of our project as Frontend, Backend and Mobile Teams, all the members in these 3 groups fully participated in both the general meetings and the in-team meetings, showing their commitment to the project and allowing our work to run in line with the project pipeline. In addition, both being able to organize the meetings face-to-face unlike the group meetings held online last semester, and the fact that the team members were in constant communication were very helpful in resolving the problems we encountered during the project implementation as quickly as possible. In addition to the aforementioned, another advantage of our division into 3 separate teams that has been working in different fields was that the general meetings held were completed in a relatively short time instead of taking too long than expected as in the previous semester. Furthermore, we ensured that the branch structure was properly organized, as in the example of master -> dev -> dev/front, so that the permanent modifications we made did not negatively impact each other's work. Finally, unlike all the other teams that made a presentation on the Milestone day, we were able to stay one step ahead, as we managed to implement the email verification page in a way that all the functionality from the backend and the frontend parts would work seamlessly and compatible with each other.

### What Could We Have Done Better Part
Even though very few, there are some areas where we, as a team, might have handled better the difficulties we had from the start of the term through the milestone delivery. Firstly, we had to spend a lot of time modifying the requirements we prepared last semester in order to satisfy the needs of the new client since our instructor, who served as the customer, changed from the term before due to circumstances beyond our control. Secondly, because of the unavoidable changes in the requirements, we were forced to update all of the software designs we had previously created. Additionally, because we had to spent our time discussing how the new diagrams we had made should function, we were unable to use that valuable time for other more productive tasks. Moreover, we may have been able to lessen the pressure of having to provide the deliverables in the final few days before the deadline if we had only taken a little more time to prepare the Milestone report.
In addition, although all three of the teams we formed were able to do the necessary unit tests on time, we left the unit testing to the relatively later stages of the project development phases, so there was some concern among the team members in the final days before the milestone delivery on whether or not we could complete them on time. Finally, although we managed to create frontend and mobile pages in a timely manner with an eye-catching and visually impressive design, the initial learning processes and code implementations of these parts took a little longer than expected, as most of the Frontend and Mobile team members were working with tools they had never experienced before.

**Comment by xltvy** [comment]
Very nice work @surmelienes1, we can add these to the group review. Closing the issue.
