### ISSUE TITLE
Preparing Milestone 2 - CMPE 451 Deliverables

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#668]
### Issue Description

I will create a new folder inside the "deliverables" folder called "CMPE451_Customer_Presentation_Milestone_2" as instructed in the Customer Milestone 2 Deliverables guidelines. I will include the related hyperlinks in the "deliverables.md" and "group_review.md" files.

In addition, each member of our team will list their contributions in the format provided under the heading "Individual Contributions Report." Each team member will also add the sections they are in charge of to the group review document in a proper format considering the Customer Milestone 2 Deliverables guidelines and the division of labor we made in our group meeting on Monday, December 5th.

### Step Details

Steps that will be performed:
- [x] Create the "CMPE451_Customer_Presentation_Milestone_2" folder
- [x] Create the "deliverables.MD" file under "CMPE451_Customer_Presentation_Milestone_2" folder
- [x] Create the "group_review.md" file under "CMPE451_Customer_Presentation_Milestone_2" folder
- [x] Create the base structure for the files with the corresponding titles mentioned in the description file
- [x] Add hyperlinks for all deliverables:
  - [x] Software Requirements Specification
  - [x] Software Design (UML)
  - [x] Scenarios and Mockups
  - [x] Project Plan
  - [x] All individuals added his/her reports

### Final Actions

These procedures will all be carried out at a different branch. The branch will be merged with the dev branch after receiving at least one member's approval.

### Responsible People

- [x] Bahrican Yesil
- [x] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [x] Onur Kömürcü
- [x] Mehmet Batuhan Çelik
- [x] Ecenur Sezer
- [x] Koray Tekin
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

08.12.2022 - Thursday - 23.59

### Reviewer

Altay Acar

### Deadline for the Review

09.12.2022 - Friday - 14.00

### Final To-Dos

- [x] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [x] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by surmelienes1** [comment]
## Conclusion

Since every team member of the group 2 has shared their individual reports and added them into the milestone 2 report, this issue will now be closed.
