### ISSUE TITLE
Milestone-2 Report: Requirements Revision

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#678]
### Issue Description

As we keep improving our application Learnify, according to our development teams' experiences and the feedback from the customer; the necessity of revising our [requirements specifications](https://github.com/bounswe/bounswe2022group2/wiki/Requirements) occurred. 
        The outcome of the meeting on "05/12/2022" was toward assigning @ezgy and me as the responsible members of the team for this revision. 

### Step Details

Steps that will be performed:
- [x] Revision of glossary. 
- [x] Questions about requirements part updates.
- [x] Base features update.
- [x] Revision of user requirements (first section of the functional requirements).
- [x] Revision of system requirements (second section of the functional requirements).
- [x] Revision of non-functional requirements.

### Final Actions

After @ezgy and I share the mentioned revision tasks between us and finalize the revision of the requirements for the time being, we will inform the other team members; after the examination of the reviewer members documentation of this revision will be provided to the customer via related report. 

### Responsible People

- [X] Ezgi Aysel Batı
- [X] Koray Tekin

### Deadline of the Issue

8.12.2022 - 22:00

### Reviewer

Ecenur Sezer

### Deadline for the Review

8.12.2022 - 24:00

### Final To-Dos

- [x] Every responsible shared an info about the sections/parts s/he will perform.
- [x] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [x] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by Koraytkn** [comment]
I have updated the [base features](https://github.com/bounswe/bounswe2022group2/wiki/Base-Features) section according to our updates about the learning spaces and desired functionalities.

**Comment by Koraytkn** [comment]
I have revised the glossary section and made the necessary changes. Most of those changes were rooting from the conversion of course - learning space and lectures/learner - co-learner. I had hesitation about removing the "achievement" definition, @ezgy your idea for this case will be appreciated.

**Comment by Koraytkn** [comment]
I have updated the [Questions about requirements](https://github.com/bounswe/bounswe2022group2/wiki/Questions-About-Requirements) section according to our new requirement specifications.

**Comment by ezgy** [comment]
I have made changes in the following sections of [Requirements](https://github.com/bounswe/bounswe2022group2/wiki/Requirements):
- 1.1.1.4. Forgot Password
- 1.1.2.10. Interests and Knowledge
- 1.1.2.14. Annotations
- 1.1.2.15. Learning Spaces and Reputation
- 1.1.2.16. Recommendation
- 1.1.3.2.1. Creating Learning Space & Content
- 1.1.3.2.2. Editing Learning Spaces
- 1.1.3.2.3. Enrolling to Learning Spaces 
- 1.1.3.2.4. Notes and Annotation
- 1.1.3.2.5. Community Events
- 1.1.3.2.6. Creating Polls
- 1.1.3.2.7. Discussions Forum
- 1.1.4 Learning Space Structure
- 1.2.1. 💡 Recommendations 
+ Some additonal grammar fixes all around.

**Comment by ezgy** [comment]
> I have revised the glossary section and made the necessary changes. Most of those changes were rooting from the conversion of course - learning space and lectures/learner - co-learner. I had hesitation about removing the "achievement" definition, @ezgy your idea for this case will be appreciated.

I agree that the requirements regarding achievements don't align with the current project plan, and I have similar questions regarding Progress tracking and reputation sections. Maybe we can leave these parts as is, for now, to discuss again with the team& customer.
