### ISSUE TITLE
Software Design: Use Case Diagram - Enrolled Course Actions

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#69]
### Issue Description

As part of designing the use case diagram, 3 main action sets have been defined. This task corresponds to the design of actions related to enrolled courses. Part of the use case diagram that includes these actions should be designed before the merging meeting. For the other action sets, see #71 . 

Don't forget to add a checkmark and link the personal issue next to your name in the "Responsible People" list.

### Step Details

Steps that will be performed should be determined by the assignees

- [x] [Note actions (Creating, editing, viewing them)](https://github.com/bounswe/bounswe2022group2/issues/80) @bahricanyesil 
- [x] [Annotation actions](https://github.com/bounswe/bounswe2022group2/issues/84) (Creating, editing, viewing them) @hasancan-code 
- [x] [Reviewing a course](https://github.com/bounswe/bounswe2022group2/issues/81) @bahricanyesil  
- [x] [Attending and viewing events](https://github.com/bounswe/bounswe2022group2/issues/82) @onurkomurcu 
- [x] [Viewing content](https://github.com/bounswe/bounswe2022group2/issues/85) @onurkomurcu 

Make sure to do a review of the actions list and add anything missing, and cross-check with requirements and mockups to validate functionality.

### Final Actions

Please share the progress and personal issues created regarding this task in the comments. As other members need to review the proposed structure before the team meeting on 02.04.2022 Saturday, it is essential to meet the deadline. 

### Deadline of the Issue

02.04.2022 14.00 Saturday

### Reviewer

Ahmet Yiğit Özdoğan @ahmet633 

### Deadline for the Review

02.04.2022 15.00 Saturday

### Final To-Dos

* Every responsible shared an info about the sections/parts s/he will perform.
* Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
* Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by ezgy** [comment]
INFO: As we have been doing since meeting #2, I will assign this issue to myself  "the issue creator" as the 'overseer' of actions performed and issue management. The responsible people can be found in the issue description and their relevant issues will be linked once created.

**Comment by bahricanyesil** [comment]
I will be dealing with the following items:

1. Creating Notes
2. Viewing Notes
3. Reviewing Courses

I will create 2 separate issues for creating&viewing notes and reviewing courses since they are related to different steps.

I will link the corresponding sub-issues after created both as comments and in the description of the issue.

**Comment by bahricanyesil** [comment]
I created a sub-issue for creating&viewing notes part. You can view the details of that part [here](#80).

**Comment by bahricanyesil** [comment]
I created a sub-issue for reviewing courses part. You can view the details of that part [here](https://github.com/bounswe/bounswe2022group2/issues/81).

**Comment by onurkomurcu** [comment]
I will be working on the following topics regarding this issue:

- [ ] View course events
- [ ] Attend event
- [ ] View content

I will create 2 sub-issues for these tasks which are **View and Attend Event** and **View Content**. My work can be observed from these sub-issues. If you have any feedback, please contribute within these issues. 

PS: Issue links can be found here and in the issue description when they are created.

**Comment by hasancan-code** [comment]
I completed the annotation actions which is my part of the job. You can check the process and the final actions from the corresponding sub-issue #84

**Comment by ezgy** [comment]
Everyone has contributed their part and it was reviewed by the whole team in a meeting. Individual issues have been linked in the comments. All work regarding this issue is done so it can be closed.
