### ISSUE TITLE
Milestone-2 Report: Updating Project Plan 

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#690]
### Issue Description

I will be updating project plan which will cover to the end of the milestone 3. 

### Step Details

Steps that will be performed:
- [x] Discuss with team members about planning
- [x] Update the project plan with using ProjectLibre app
- [x] Add updated project plan to milestone-2 report
- [x] Add updated project plan to our wiki page

### Final Actions

When the work is done, it will be provided here to be reviewed as well.

### Deadline of the Issue

08.12.2022 - 23.59

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

09.12.2022 - 12.00

**Comment by onurkomurcu** [comment]
I have updated the project plan according to our team discussions. PDF of the project plan can be seen below and also from [related wiki page](https://github.com/bounswe/bounswe2022group2/wiki/Project-Plan)

[CmpE451_ProjectPlan_Milestone2.pdf](https://github.com/bounswe/bounswe2022group2/files/10195331/CmpE451_ProjectPlan_Milestone2.pdf)
