### ISSUE TITLE
Milestone-2 Report: Individual Report

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#691]
### Issue Description

As mentioned in #668, the Individual contribution report of @codingAku needs to be documented. The report will include my review of our second demo, unit tests I have implemented so far, and issues & pull requests I have created for Milestone-2. 

### Step Details

Steps that will be performed:
- [ ] Document my review
- [ ] Link issues and pull requests
- [ ] Include unit tests

### Final Actions

The related PR review and merge will close this issue.

### Deadline of the Issue

8.12.2022 - 00.00

### Reviewer

Koray Tekin

### Deadline for the Review

9.12.2022 - 14.00

**Comment by codingAku** [comment]
The related PRs for both deliverables.md and group-review.md are open.
#692 and #693
