### ISSUE TITLE
Milestone-2 Report: Individual Report

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#696]
### Issue Description

As mentioned in https://github.com/bounswe/bounswe2022group2/issues/668, every member should add their individual contributions to the milestone 2 report.

The report will include:
- responsibilities
- main contributions
- significant issues
- pull requests
- unit tests
- "Summary of Individual Work" table 

### Step Details

Steps that will be performed:
- [ ] add responsibilities
- [ ]  add main contributions
- [ ] add significant issues
- [ ]  add pull requests
- [ ] add unit tests
- [ ]  add "Summary of Individual Work" table 

### Final Actions

All required sections will be added to the report and a pr will be opened. Since I had problems last milestone and had to re-write everything, this time all contributions will be addded on a allocated branch until merging.

### Deadline of the Issue

09.12.2022

### Reviewer

Ecenur Sezer
