### ISSUE TITLE
Milestone 2: Individual Report - Bahrican Yesil

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#701]
### Issue Description

As mentioned in #668, the Individual contribution report of @bahricanyesil needs to be documented. The report will include my review of our second demo, unit tests I have implemented so far, and issues & pull requests I have created for Milestone-2. 

### Step Details

Steps that will be performed:
- [x] Link issues and pull requests
- [x] Include unit tests
- [x] Responsibilities
- [x] Main contributions
- [x] Significant issues
- [x] "Summary of Individual Work" table 

### Final Actions

The related PR review and merge will close this issue.

### Deadline of the Issue

09.12.2022 - 14.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

09.12.2022 - 16.00

**Comment by bahricanyesil** [comment]
I've completed all steps mentioned in the issue description. I filled my sections in both deliverables.md and group_review.md files. Here're the corresponding PRs:

For deliverables.md: [Individual Contribution Report](https://github.com/bounswe/bounswe2022group2/pull/707)
For group_review.md: [Summary of Work Table](https://github.com/bounswe/bounswe2022group2/pull/708)

**Comment by bahricanyesil** [comment]
Now, this issue and all PRs are ready to be reviewed.

**Comment by bahricanyesil** [comment]
Waiting for review by @onurkomurcu.

**Comment by bahricanyesil** [comment]
Two PRs are reviewed, approved, and merged. Therefore, this issue is also automatically closed since it is linked.
