### ISSUE TITLE
Milestone-2 Report: Progress According To Requirements

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#705]
### Issue Description

For our second milestone report, we are asked to review our progress according to our requirements. After revision of our requirements is completed, @egemenatikk and @gokayyildiz will review our project's progress according to our requirements in terms of front-end part, back-end part and mobile part.

### Step Details

Steps that will be performed:
- [x] Review the revised requirements
- [x] Decide those requirement's progress status (not started, in progress or completed)
- [x] Document progress according to requirements in terms of front-end, back-end and mobile parts

### Final Actions

After this task is completed and approved by the reviewer, this issue will be closed and related part will be added to our group's second milestone report.

### Responsible People

- [ ] Egemen Atik
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

09.12.2022 - Friday - 15:00

### Reviewer

Ecenur Sezer

### Deadline for the Review

09.12.2022 - Friday - 16:00

### Final To-Dos

- [ ] Every responsible shared an info about the sections/parts s/he will perform.
- [ ] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [ ] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by gokayyildiz** [comment]
I reviewed the requirements and created the part that is related to making a report on the progression according to the requirements. I wrote all frontend related and most of the backend related progress.

**Comment by egemenatikk** [comment]
I reviewed the requirements and filled the rest of the related part in the general group report for milestone 2. I filled all mobile related progress and remaining backend progress.
