### ISSUE TITLE
Milestone-2 Report: Individual Report

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#706]
### Issue Description

According to #668, every member should add their individual contributions report to the group's second milestone report. Indiviual contributions report should include the followings:

* responsibilities
* main contributions
* significant issues
* pull requests
* unit tests
* "Summary of individual work" table

### Step Details

Steps that will be performed:
- [x] Add responsibilities
- [x] Add main contributions
- [x] Add significant issues
- [x] Add pull requests
- [x] Add unit tests
- [x] Add "Summary of individual work" table

### Final Actions

After all steps mentioned above is completed, I will open a pull request to add my indiviual report to general group report for second milestone. Merging that pull request will close this issue.

### Deadline of the Issue

09.12.2022 - Friday - 15:00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

09.12.2022 - Friday - 16:00
