### ISSUE TITLE
Milestone 2: Fill User Interface Part for Mobile

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#710]
### Issue Description

As it is described in the customer milestone 2 description pdf file, we need to create a title named "User Interface / User Experience". The details of this part are given as follows in the description:
- For each user interface design, provide links to the code in the project repository
- Screenshots of all implemented Web and Mobile interfaces

Therefore, as the mobile team, we need to fill this section with the screenshots, and code links of the screens/designs we implemented. Each team member will fill this section with his/her own implemented features.

### Step Details

Steps that will be performed:
- [x] Bahrican added the designs/screens he implemented @bahricanyesil 
- [x] Egemen added the designs/screens he implemented @egemenatikk 
- [x] Onur added the designs/screens he implemented @onurkomurcu 
- [x] Ezgi added the designs/screens she implemented @ezgy 

### Final Actions

PRs will be opened by each member for this issue. After all team members added his/her sections or the deadline has passed, the issue will be closed.

### Deadline of the Issue

09.12.2022 - 16:00

### Reviewer

Egemen Atik

### Deadline for the Review

09.12.2022 - 16:30

**Comment by bahricanyesil** [comment]
I've added the screens/designs I implemented under the UI/UX section of the milestone-2 report. I've added screenshots, code links, and descriptions in the required places.

[Here's the corresponding PR](https://github.com/bounswe/bounswe2022group2/pull/715/), it is ready to be reviewed by @egemenatikk.

**Comment by bahricanyesil** [comment]
My PR is merged and the parts I implemented are added to the group review file.

You can see them [here](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md#user-interfaceuser-experience).

**Comment by ezgy** [comment]
screens implemented by me have been added to the milestone 2 report. The change proposed is on pr #720

**Comment by onurkomurcu** [comment]
I have added the parts that I implemented. Further details can be found under PR #737

**Comment by egemenatikk** [comment]
Mobile screens implemented by me are added to general group report for milestone-2. You can view the corresponding pull request from #738.

**Comment by egemenatikk** [comment]
Since every member of mobile team have added screenshots of screens implemented by them to general group report and all pull requests are merged, this issue can be closed.
