### ISSUE TITLE
Milestone 2: Individual Report - Muhammed Enes Sürmeli

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#711]
### Issue Description

The individual contribution report of @surmelienes1 has to be documented, as was suggested in #668. My evaluation of our second demo, the unit tests I have so far developed, and the issues and pull requests I have created for Milestone-2 are all included in the report.

### Step Details

Steps that will be performed:
- [ ] Link issues and pull requests
- [ ] Include unit tests
- [ ] Responsibilities
- [ ] Main contributions
- [ ] Significant issues
- [ ] Summary of Individual Work" table

### Final Actions

I will create a separate branch to address this specific issue. After completing all of the above activities, I will generate a pull request in accordance with the issue. I will be committing the modifications to that branch throughout the process. This issue will be resolved once the PR is accepted and integrated into our master branch.

### Deadline of the Issue

09.12.2022 - Friday - 14.00

### Reviewer

Altay Acar

### Deadline for the Review

09.12.2022 - Friday - 16.00
