### ISSUE TITLE
Milestone 2: Release documentation

### ISSUE THREAD

**Issue by mbatuhancelik** [bounswe/bounswe2022group2#713]
### Issue Description

I was responsible for creating a tag, release and write release description as well as provide docker run instructions for the milestone 2.
This issue is for tracking my responsibilities regarding milestone 2 documentation.

### Step Details

Steps that will be performed:
- [x] Create a new tag for the release
- [x] Get the release
- [x] Provide docker run instructions.
- [x] Write release documentation

### Deadline of the Issue

09.12.2022 Friday 17:00

### Reviewer

Ecenur Sezer

### Deadline for the Review

09.12.2022 Friday 15:00

**Comment by mbatuhancelik** [comment]
Closing this as milestone 2 is submitted.
