### ISSUE TITLE
Milestone-2: Individual Report

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#714]
### Issue Description

According to https://github.com/bounswe/bounswe2022group2/issues/668, every member should add their individual contributions report to the group's second milestone report. So, I will also do it. 

### Step Details

Steps that will be performed:
- [x] Add responsibilities
- [x] Add main contributions
- [x] Add significant issues
- [x] Add pull requests
- [x] Add unit tests
- [x] Add "Summary of individual work" table

### Final Actions

After the work is done, related PR's will be provided here to be reviewed.

### Deadline of the Issue

09.12.2022 - 15.00

### Reviewer

Bahrican Yesil

### Deadline for the Review

09.12.2022 - 16.00

**Comment by onurkomurcu** [comment]
As it can be seen, related tasks are merged under #725 and #731. Further details can be found under this PR's.
