### ISSUE TITLE
Milestone-2: Status of Deliverables of Milestone 1

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#718]
### Issue Description

In the Milestone Report 1, listed deliverables are below:
* Software Requirements Specification
* Software Design (UML)
* Scenarios and Mockups
* Project Plan
* Individual Contribution Reports
* Software
* Mobile Deliverables (Manual, APK)
* Group Review (This Document)

For the milestone report 2, I am responsible to examine the status of the deliverables and report any changes, updates made in between.

### Step Details

Steps that will be performed:
- [x] Examine the status of deliverables during the milestone report 1
- [x] Examine the current status of deliverables
- [x] Compare both
- [x] Provide reports accordingly

### Final Actions

After I have performed all the steps mentioned above, I will add them to the group review file in the milestone report 2.

### Deadline of the Issue

09.12.2022 - Friday - 15.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

09.12.2022 - Friday - 16.59

**Comment by xltvy** [comment]
## Update

I have documented the report comparing everything by their current states. Below are the results:

### *Software Requirements Specification*

Since the requirements specification of our project was done when there is not any implementation progress going on, although most of the application’s structure is coherent with the requirements specification from milestone 1, some changes are made because of the implementation: We have added image annotation feature. We have changed the content type of learning spaces from chapters to posts so that learning is not received but achieved with collaborative effort. Because of the same reason, the creator of the learning space and the participants are now not separated by themselves, they all listed as contributors. In accordance to all these big updates that resulted from the implementation and customer meetings between the milestones 1 and 2, we have updated relevant sections of software requirements specification.

### *Software Design (UML)*

There was not any significant changes in the software design diagrams between the milestones 1 and 2.

### *Scenarios and Mockups*

There was not any significant changes in the scenarios and mockups between the milestones 1 and 2. However, since those scenarios are outdated and used for only the very first days of the development of our application and did not feature anything related the real scenarios, we have used different scenarios in our customer presentation.

Web application’s demo featured Mehmet, a new grad who just bought a new home and wants to learn some tips and recipes to follow in his new kitchen. Mehmet log ins to Learnify, browses categories and find the suitable category. Then, finds a learning space that raises his interest, joins that learning space, and upvotes a content that he really likes. Then, he is amazed by the idea of sharing the knowledge. So, he creates his own learning space about pottery, and adds his first post. Because he mistakenly misspelled a word during adding the post, he edits the post. He is also good at electro guitar. So, he searches for any learning spaces about it. But because he is a bit lazy he only writes guitar to the search bar, but he finds the learning space he was looking for. He spots some false information in the posts of that learning space and points those mistakes out by adding annotation.

### *Project Plan*

There was not any significant changes in the project plan between the milestones 1 and 2.

### *Individual Contribution Reports*

Individual contribution reports feature any contribution of each member between the milestones 1 and 2, strongly featuring development of our application’s core parts such as but not limited to home, learning spaces, posts, annotations, semantic search. Each team member provided their own contributions in tabular format.

### *Software*

Between the milestones 1 and 2 our software has been through big updates and now its version is updated from 0.1.0-alpha to 0.2.0-alpha. In the first milestone, all the authentication related part of our application was finished completely. In this version for the milestone 2, it now features a home page, fully functioning learning space content, contributors and annotations. Also, it features semantic search, which is now only limited to searching for learning spaces. Now, a user can create a learning space, join a learning space, add posts, annotate any content, search for learning spaces, browse categories and learning spaces by category.

### *Mobile Deliverables (Manual, APK)*

There was not any significant changes in the project plan between the milestones 1 and 2.

### *Group Review (This Document)*

Group review features the review of the work done by the whole group between the milestones 1 and 2, strongly featuring development of our application’s core parts such as but not limited to home, learning spaces, posts, annotations, semantic search.

***

Since I am not technically capable of explaining significant changes for Mobile Deliverables, I have left that part as unchanged. But if necessary mobile team (@bahricanyesil , @ezgy , @onurkomurcu ) can add explanations there. Also, adding the mobile team's scenario in the presentation would be nice.

Besides, when the project plan is done and updated, @onurkomurcu can add some quick explanation here.

If no changes necessary, I will create a PR accordingly. If changes necessary, I will create PR when the changes are made.

**Comment by xltvy** [comment]
## Update

Since the deadline is close, I am publishing this part as it is right now.
