### ISSUE TITLE
Milestone 2: Annotations Part of the Report - Mobile

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#719]
### Issue Description

We have an annotations title for the milestone-2 report. @codingAku has already done a great job of filling this section with information about the status, standards, future improvements, and so on. I will add some specific information about the mobile side of the annotations and I will also attach screenshots related to the annotation feature.

### Step Details

Steps that will be performed:
- [ ] Give information about the mobile process on annotations
- [ ] Add related screenshots for the annotation feature on the mobile app
- [ ] Provide a mobile plan for annotations

### Final Actions

After all of the steps mentioned are completed on a separate branch, a PR will be opened. When the PR is reviewed and merged, the issue will also be closed.

### Deadline of the Issue

09.12.2022 - 16:00

### Reviewer

Onur Kömürcü

### Deadline for the Review

09.12.2022 - 16:30

**Comment by bahricanyesil** [comment]
I've completed all steps mentioned in the issue description. I opened a PR for the changes implemented regarding to this issue, here is the PR: #734.

**Comment by bahricanyesil** [comment]
The PR is reviewed, approved, and merged. Therefore, the issue is also closed.
