### ISSUE TITLE
Milestone-2: User Interfaces for Web Application

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#723]
### Issue Description

As part of the milestone 2 report, we need to add the user interfaces we have designed for the web application as the frontend team. We have decided to distribute the work by each member adding the interfaces they have worked on.

This issue is the main issue of web application's user interfaces. Each member will add their own interface works' screenshots and provide hyperlinks to the code accordingly in the milestone 2 report.

### Step Details

Steps that will be performed:
- [x] @xltvy will add screenshots and provide hyperlinks
- [x] @gokayyildiz will add screenshots and provide hyperlinks
- [x] @Koraytkn will add screenshots and provide hyperlinks
- [x] @surmelienes1 will add screenshots and provide hyperlinks

### Final Actions

After everyone has added their part to the milestone report 2, this issue will be closed.

### Deadline of the Issue

09.12.2022 - Friday - 16.00

### Reviewer

Koray Tekin

### Deadline for the Review

09.12.2022 - Friday - 16.59

**Comment by xltvy** [comment]
I have added my part of the web application's ui designs, can be tracked from #729

**Comment by gokayyildiz** [comment]
I have added my part, after [the pr](https://github.com/bounswe/bounswe2022group2/pull/732) is merged it will be in the master

**Comment by surmelienes1** [comment]
## Update

I have added my part of the web application's ui designs, can be tracked from https://github.com/bounswe/bounswe2022group2/pull/744

**Comment by xltvy** [comment]
Since everyone added their parts, closing this issue.
