### ISSUE TITLE
Preparing Milestone 3 - CMPE 451 Final Deliverables

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#934]
### Issue Description

I will create a new folder inside the "deliverables" folder called "CMPE451_Customer_Presentation_Milestone_3" as instructed in the Customer Milestone 3 Deliverables guidelines. I will include the related hyperlinks in the "final_deliverables.md" file.

In addition, each member of our team will list their contributions in the format provided under the heading "Individual Contributions Report." Each team member will also add the sections they are in charge of to the group review part in a proper format considering the Customer Milestone 3 Deliverables guidelines and the division of labor we made in our group meeting on Friday, December 30th.

### Step Details

Steps that will be performed:
- [x] Create the "CMPE451_Customer_Presentation_Milestone_3" folder
- [x] Create the "final_deliverables.md" file under "CMPE451_Customer_Presentation_Milestone_3" folder
- [x] Create the base structure for the files with the corresponding titles mentioned in the description file
- [x] Add hyperlinks for all deliverables:
    - [x] Software Requirements Specification
    - [x] Software Design (UML)
    - [x] Scenarios and Mockups
    - [x] Project Plan
    - [x] All individuals added his/her reports

### Final Actions

These procedures will all be carried out at a different branch. The branch will be merged with the dev branch after receiving at least one member's approval.

### Responsible People

- [x] Bahrican Yesil
- [x] Egemen Atik
- [x] Altay Acar
- [x] Ezgi Aysel Batı
- [x] Muhammed Enes Sürmeli
- [x] Onur Kömürcü
- [x] Hasan Can Erol
- [x] Mehmet Batuhan Çelik
- [x] Ecenur Sezer
- [x] Koray Tekin
- [x] Mehmet Gökay Yıldız

### Deadline of the Issue

02.01.2023 - Tuesday - 16.00

### Reviewer

Mehmet Gökay Yıldız

### Deadline for the Review

02.01.2023 - Tuesday - 23.59

### Final To-Dos

- [ ] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [ ] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by surmelienes1** [comment]
## Update

I have completed the preparations for the Milestone 3 final_deliverables.md file. All the related work about this issue can easily be tracked from the pull request #935

**Comment by surmelienes1** [comment]
## Conclusion

Since every member of our team has completed their progress on writing their individual contributions reports in the Milestone 3 final_deliverables.md file and shared all their related works from separate issues and pull requests, I will now close this issue.
