### ISSUE TITLE
Final Milestone-3 Report: Executive Summary

### ISSUE THREAD

**Issue by bahricanyesil** [bounswe/bounswe2022group2#936]
### Issue Description

As we have decided in our group meeting on December 30th, I will fill the executive summary section of our final milestone report. The executive summary section in the report consists of several sub-titles. I will fill all of them except the "Status of Deliverables" and "Final release notes" subtitles.

### Step Details

Steps that will be performed consist of filling in the following sections:
- [x] Summary of the Project Status
- [x] Changes the Team Has Made or Planned Since Milestone 2 to Improve Development Process, and How Those Changes Have Impacted the Process
- [x] Reflections Related to the Final Milestone Demo Including Lessons Learned
- [x] What Could Be Done Differently at the Start of the Project to Finalize the Project

### Final Actions

After all of the steps mentioned are completed on a separate branch, a PR will be opened. When the PR is reviewed and merged, the issue will also be closed.

### Deadline of the Issue

02.01.2023 - Tuesday - 16.00

### Reviewer

Muhammed Enes Sürmeli

### Deadline for the Review

02.01.2023 - Tuesday - 23.59

**Comment by bahricanyesil** [comment]
All steps mentioned in the issue description are completed. Right now, the annotations are connected to the newly created microservice. A corresponding PR will be opened.

**Comment by bahricanyesil** [comment]
The corresponding PR is opened which includes the implementation of the steps mentioned in this issue. You can view it here #937. Now, it is ready to be reviewed by @surmelienes1.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @bahricanyesil for your valuable contributions! Since I have merged the changes you have made with the master branch to continue working on the final milestone report, I will now close this issue.
