### ISSUE TITLE
Final Milestone: Status of the Requirements

### ISSUE THREAD

**Issue by gokayyildiz** [bounswe/bounswe2022group2#944]
### Issue Description

As the term reached to the end, we should review ourselves in terms of the goals that we have set at the beginning of the semester and what we have achieved at the end of the semester.

### Step Details

Steps that will be performed:
- [x] Review of Functional requirements
- [x] Review of the nonfunctional requirements
- [x] Review for both frontend, backend and mobile

### Final Actions

After that I have reviewed the requirements and filled the review part in the milestone deliverables. I will open a PR and merge my updates to the group deliverables

### Deadline of the Issue

02.01.2023 - Monday - 11.59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

02.01.2023 - Monday - 19.59

**Comment by gokayyildiz** [comment]
Steps are completed and pr is open #945, needs review @ezgy
