### ISSUE TITLE
Final Milestone: UML Diagrams, SRS, User Scenarios and Mockups

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#946]
### Issue Description

Under ***2-Project Artifacts*** title of final milestone file, we are asked to add our UML diagrams(use-case diagram, class diagram and sequence diagram), software requirements specification, user scenarios and mockups to our final milestone report. I was assigned with this task in our last meeting. I will take screenshots of all necessary parts and add them with necessary texts to our final milestone report.

### Steps that will be performed:
- [x] Add software requirements specifications
- [x] Add UML diagrams (use-case diagram, class diagram, sequence diagram)
- [x] Add user scenarios and mockups

### Final Actions

After I complete my task, I will open a corresponding pull request. Merging that pull request will close this issue.

### Deadline of the Issue

02.01.2023 - Monday - 13:00

### Reviewer

Ezgi Aysel Batı

**Comment by egemenatikk** [comment]
Corresponding pull request, #947, is opened. Merging that pull request will automatically close this issue.
