### ISSUE TITLE
Final Milestone: Individual Contributions Report for Enes Sürmeli

### ISSUE THREAD

**Issue by surmelienes1** [bounswe/bounswe2022group2#948]
### Issue Description

The individual contribution report of @surmelienes1 has to be documented, as was suggested in https://github.com/bounswe/bounswe2022group2/issues/934. My evaluation of our final demo, the unit tests I have so far developed, and the issues and pull requests I have created for Milestone-3 and the first two milestones are all included in the report.

### Step Details

Steps that will be performed:
- [x] Include member information
- [x] Link issues and pull requests
- [x] Include unit tests
- [x] Responsibilities
- [x] Main contributions
- [x] Significant issues
- [x] Additional information

### Final Actions

I will create a separate branch to address this specific issue. After completing all of the above activities, I will generate a pull request in accordance with the issue. I will be committing the modifications to that branch throughout the process. This issue will be resolved once the PR is accepted and integrated into our master branch.

### Deadline of the Issue

02.01.2023 - Monday - 16.00

### Reviewer

Bahrican Yesil

### Deadline for the Review

02.01.2023 - Monday - 22.59

**Comment by surmelienes1** [comment]
## Update

I have completed my progress on writing my individual contributions report in the Milestone 3 final_deliverables.md file. All the related work about this issue can easily be tracked from the pull request #989

**Comment by surmelienes1** [comment]
## Conclusion

Since related pull request https://github.com/bounswe/bounswe2022group2/pull/989 has been merged, I will now close this issue.
