### ISSUE TITLE
Final Milestone: User Manual

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#951]
### Issue Description

Under ***2-Project Artifacts*** title of final milestone file, we are asked to add a user manual to our final milestone report. I was assigned with this task in our last meeting. I will create a wiki page for user manual and also add content of that page to our final milestone report.

### Step Details

Steps that will be performed:
- [x] Create a wiki page for user manual
- [x] Take screenshots of our application and prepare user manual
- [x] Add content of user manual wiki page to the final milestone report
- [x] Add link of user manual wiki page to sidebar and home wiki page

### Final Actions

After I complete my task, I will open a corresponding pull request. Merging that pull request will close this issue.

### Deadline of the Issue

02.01.2023 - Monday - 16:00

### Reviewer

Ezgi Aysel Batı

**Comment by egemenatikk** [comment]
User manual wiki page is prepared, you can view it from [here](https://github.com/bounswe/bounswe2022group2/wiki/User-Manual).

**Comment by egemenatikk** [comment]
Corresponding pull request, #984, is opened. Merging that pull request will automatically close this issue.

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @egemenatikk for your valuable contributions! Since I have merged the changes you have made with the master branch to continue working on the final milestone report, I will now close this issue.
