### ISSUE TITLE
Final Milestone: Annotations & Standards

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#952]
### Issue Description

As part of our Final Milestone for Learnify application, we need to update the status of the annotations used in the application and the W3C standards that we follow for them.

Deliverables:

Updated documentation for the annotations and W3C standards used in Learnify

### Step Details

The task involves the following:

- [x] Review the current status of the annotations used in Learnify. 
- [x] Update the documentation for Learnify to reflect the current status of the annotations. This includes removing any references to deprecated or obsolete annotations and adding documentation for any new annotations.
- [x] Review the W3C standards that Learnify currently follows, and update the documentation to reflect any changes or updates to these standards.

### Final Actions

The merge of the related pull request to deliverables will close the issue.

The issue is related to #935 

### Deadline of the Issue

2.01.2023 - 17.00

### Reviewer

Altay Acar

### Deadline for the Review

2.01.2023 - 19:00

**Comment by codingAku** [comment]
Related PR merged and closed.
