### ISSUE TITLE
Final Milestone : API Documentation

### ISSUE THREAD

**Issue by codingAku** [bounswe/bounswe2022group2#953]
### Issue Description

This task includes documenting all API endpoints, request and response structures, and any relevant notes or examples for each API. It is important to ensure that all APIs are properly documented so that they can be easily understood and used by developers working on the Learnify app. The backend team members @mbatuhancelik and @codingAku will document the APIs.

### Step Details

Steps that will be performed:
**For each API:**

- [x] Create a new request in the Postman collection
- [x] Enter the API endpoint and method (e.g. GET, POST)
- [x] Define the request parameters (if any) and their data types
- [x] Define the request body (if applicable) and its structure
- [x] Define the response structure and any relevant response codes
- [x] Add any notes or examples to help developers understand how to use the API
- [x] Submit the completed Postman collection for review.

### Final Actions

After the postman documentation is ready, it will be added to the final deliverables.

This issue is related to #935 

### Deadline of the Issue

2.01.2023 - 17.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

2.01.2023 - 19:00

**Comment by onurkomurcu** [comment]
Thank you for your great work, @mbatuhancelik @codingAku !
