### ISSUE TITLE
Final Milestone: Web Application Scenario

### ISSUE THREAD

**Issue by xltvy** [bounswe/bounswe2022group2#955]
### Issue Description

As part of the final milestone report for our project, we need to include a scenario that covers the functionalities of our web application. The scenario should be detailed and should cover every single functionality of the application.

### Step Details

Steps that will be performed:
- [x] Review the functionalities of the web application to make sure having a thorough understanding of how it works.
- [x] Write a scenario that includes detailed descriptions of each functionality, including any relevant interactions or actions that the user can take.
- [x] Check that the scenario covers every single functionality of the web application and that it is easy to follow and understand.
- [ ] Submit the completed scenario for the milestone documentation.

### Final Actions

After I prepare the scenario that fits the needs of what described above, I will share it here. When, it is reviewed and revisions made if necessary, I will add it to our final milestone report by opening a pull request accordingly.

### Deadline of the Issue

02.01.2023 - Monday - 19.00

### Reviewer

Onur Kömürcü

### Deadline for the Review

02.01.2023 - Monday - 20.00

**Comment by xltvy** [comment]
## Update

I have prepared the web application's scenario, now it is ready for a review from @onurkomurcu. You can view it from below:

***

Our scenario follows a senior student Gökay, who has a very relaxed weekly schedule in his final semester in the university. Thus, he is very eager to learn new things and develop himself in different areas of life. As a student, he has heard about an online learning platform called Learnify from one of his friends in the university, and he decides to check it out.

He navigates to the website and sees that he can sign up for an account by entering his email address, choosing a username, and setting a password with confirmation. He also needs to read and agree on terms of use on KVKK by clicking the checkbox in the form. He completes the sign-up process and receives an email to verify your account.

Once he’s verified his account, he is able to log in to Learnify. But, because he is a bit distracted about everything going on, he immediately forgets his password. Thus, instead of logging in he clicks the forgot password button and gets another verification email regarding the password. Once verified, he logs in to his newly created account.

He sees that there is a search bar at the top of the page, and he decides to try it out by searching for “painting.” Because he wants to learn how to paint an oil painting in the atelier he has made for himself in his new home. He sees a list of learning spaces that matches your search query. The listed learning spaces vary from sculpting to art history, or basic charcoal sketching. He notices that the search feature also supports semantic search, so he can find learning spaces by searching for related keywords instead of the exact name of the learning space. Although he planned to learn how to create oil paintings, the charcoal sketching learning space immediately catches his attention and he wants to discover more about the topic.

He clicks on the learning space about charcoal sketching that caught his eye, and sees that it has a page with lots of content in it: information about the learning space, including a description and a title, space part where lots of content is posted, a list of contributors, and a list of upcoming events. He also sees that there is a create event button. He sees that the events component shows a list of all the events that have been created for the learning space, and he can view more details about each event such as event title, description, date and time, participation limit, duration, and its location on the map by clicking on it. He can also see the participants of that event. He also sees that the contributors section shows a list of all the users who have joined the learning space or the one who created it, and he can view their profiles by clicking on their username.

After surfing on the content posted he really likes the knowledge he can gain from here. So, he decides to join the learning space, and he sees his username on the contributors section immediately after joining the learning space as a contributor. He also sees that the creator of the learning space can be spotted by its different icon in the contributors' part. He sees that he has the ability to post content, comment on other people's posts, and annotate text or image content. He decides to create a new post by clicking on the “Add Post" button. A new section pops up and he adds a post by adding a post title, an optional link to an image and using a flexible rich editor any content he wants to add. He has a book about a beginner's guide on charcoal sketching in his library, he remembers that there was very useful information for starters. So he adds the things he remembers from the book as a post. He also adds an embedded video from YouTube using the rich editor and also adds an informative image for his post. When he’s finished, he clicks submit to post his content to the learning space.

Amazed by the idea about how people exchange their knowledge and expertise on the things they are interested in collaboratively, he immediately wants to create a learning space about playing drums. He has been a very skilled drummer since his primary school days. He even plays as the lead drummer of the rock band with his friends and they just released a new single called “Embed Me to Your Heart Like a Microcontroller.” So, he goes back to the home page by clicking the “Home” button in the navigation bar. He sees the create a learning space button and clicks it. He is redirected to a form page where he needs to fill the necessary form fields to create a learning space. He gives the title of “Play Drums Like a Boss” and provides a short description. He sees the available categories for his learning space and spots the “Music” category among the all 18 categories available. He also selects a vibrant icon for his cool learning space. When he submits the form he is redirected to this new learning space’s page, sees himself as the creator of the learning space in the contributors part and already joined. He adds the first post by giving some basic instructions on each drum and cymbal type on a drum kit. Since his new single is just released and he has a very long and amazing drum solo in that single, he thinks that adding its video as a comment to the post would be informative and also boost up his popularity on YouTube. Thus, he clicks the comments section and adds a comment with his new single’s video embedded using the rich editor again.

Before getting done with this new learning space he gets a really good idea to invite people to his band’s gig on Saturday. So, he creates an event about his gig by providing event title, description, date and time, and also duration. Since the place is not that big he sets a participation limit of 50 people and selects the location using the map picker element in the event form. After he submits the event, he sees that his event is listed in the events section of the learning space with all the data he has given just before. He also sees himself as a participant in the event’s participants list. Just before returning to the home page, he sees two other people join his learning space and even one of them has upvoted his first post. He also sees that the comment count is not what he has left off. So, he immediately clicks the comment section and sees that one of the new contributors to the learning space just replied that she loved his new single and the drum solo was amazing. He is so happy about the praise he got. So, he upvotes her comment.

When he comes back to the home page, he sees that there are some learning spaces listed on the recommended learning spaces part, since he is engaged with the application for the time being. He sees that “Electro Guitar” learning space is also recommended for him. He clicks it and goes to the learning space. He sees that there is tons of content in the learning space, almost 40 posts and 30 contributors. He thinks it would be valuable to join this learning space, since he can also share information on electro guitar about what he has learned from his friends from the band. In one of the posts he sees a mistake about playing electro guitar to a drum roll. So, using the text annotation he selects that sentence and corrects the mistake by adding what he knows about the situation. He also sees some words and sentences in the same post are already marked, showing that this part of the content is also annotated by other users. He checks on what other users have said upon the content and immediately sees that they have also corrected lots of mistakes according to their expertise. Thus, he believes that this content is not appropriate for people who want to learn to play the electric guitar and so downvotes the post. In another post he saw that someone shared a photo of one the most famous rock groups of all time “The Beatles” when they were playing in a live concert. He also spots that the head of one of the members of the group is also marked with a rectangular shape. When he clicks it, he sees that it is an image annotation asking about who he is. Since he knows every member well, Gökay decides to select each member and provide their names as image annotation. 

He remembers the friend of his who suggested him Learnify. Thus, he wants to search for her username to see her profile. He clicks the toggle button next to the search bar to switch between learning space search and the user search. He types her username, and goes to her profile by clicking the search result. He sees her profile picture, bio, and all the learning spaces she participated in. He sees a variety of learning spaces regarding the programming category. He notes himself that he will check the category catalog of the application. But first, he wants to edit his profile. Because he was a bit jealous of his friend’s rich profile. So, he clicks on the profile button on the navigation bar to reach out to his profile page. He adds an avatar and gives a nice bio for himself. He also sees the learning spaces “Play Drums Like a Boss” and “Charcoal Sketching” listed on the my learning spaces part of his profile too.

Finally, he clicks the categories button in the navigation bar to browse through categories. He sees that there are 18 categories and each of them has their own page containing learning spaces about that category and can view all of the learning spaces in a particular category by clicking on the category name. He reminds himself to check on gastronomy and culinary category later when the new furniture he has ordered for the kitchen for his new home arrives.

**Comment by onurkomurcu** [comment]
The user, Gökay, signs up for an account and is able to easily search for and access a variety of learning spaces on the platform. Gökay is impressed by the platform's features, including the ability to search for related keywords and the option to create and participate in events. He also enjoys the ability to post and comment on content within the learning spaces he joins. Overall, Gökay seems to have a positive experience with Learnify and is inspired to create his own learning space on the platform. That is a great scenario for covering up the whole platform. Thank you for your work, @xltvy !
