### ISSUE TITLE
Final Milestone: Project Plan

### ISSUE THREAD

**Issue by onurkomurcu** [bounswe/bounswe2022group2#956]
### Issue Description

I will update project plan for the last time. I am happy to use last time ProjectLibre app in my life (hopefully 😄). 

### Step Details

Steps that will be performed:
- [x] Review last project plan
- [x] Remove undone tasks from the previous project plan
- [x] Add necessary tasks for the future

### Final Actions

When the work is done, final version will be uploaded to corresponding wiki page. I will provide a link here as well.

### Deadline of the Issue

02.01.2023 - Monday - 20.00

### Reviewer

Koray Tekin

### Deadline for the Review

02.01.2023 - Monday - 21.00

**Comment by onurkomurcu** [comment]
The final part of the milestone has changed and ready to be reviewed by @Koraytkn.
![Screenshot 2023-01-02 at 16 37 01](https://user-images.githubusercontent.com/92719802/210238750-2dc9d839-ac11-48f3-afef-b4909be35803.png)

**Comment by onurkomurcu** [comment]
I couldn't changed the writing "milestone1" below each page. However, it is updated project plan.
