### ISSUE TITLE
Final Milestone: System Manual

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#961]
### Issue Description

A section system manual should be added to the final milestone report. A system manual for APK creation of mobile was previously created by me (see on [wiki](https://github.com/bounswe/bounswe2022group2/wiki/System-Manual)). This part will be updated and added to the report  with any additional information. 

### Step Details

Steps that will be performed:
- [x] Update system manual for mobile
- [x] Add system requirements and installation instructions for the web
- [x] combine and add to final report

### Deadline of the Issue

02/01/2023

### Reviewer

Egemen Atik

### Deadline for the Review

02/01/2023

**Comment by ezgy** [comment]
The system manual has been updated on the wiki and linked on the final milestone report.
