### ISSUE TITLE
Final Milestone: User Interface / User Experience

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#962]
### Issue Description

Every screen implemented on mobile and web should be listed on the final report with screenshots and links to the code in the repository. Web part will be added by @Koraytkn and mobile part will be added by me(@ezgy). 

### Step Details

Steps that will be performed:
- [x] Add screenshots of all web pages
- [x] Link relevant repository code with the web pages
- [x] Add screenshots of all mobile screens
- [x] Link relevant repository code with the mobile pages 

### Final Actions

Everything will be added to the [Finak Milestone Report](https://github.com/bounswe/bounswe2022group2/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md) as they are completed.

### Responsible People

- [x] Ezgi Aysel Batı
- [x] Koray Tekin

### Deadline of the Issue

02/01/2023

### Reviewer

Onur Kömürcü

### Deadline for the Review

02/01/2023

### Final To-Dos

- [x] Every responsible shared an info about the sections/parts s/he will perform.
- [x] Every responsible mentioned the sub-issue contains the details of his/her work, if a sub-issue is created.
- [x] Every responsible mentioned this issue in the description of his/her sub-issue, if a sub-issue is created.

**Comment by ezgy** [comment]
I have added screenshots and repository links of the mobile screens. This addition is on pr #967 and ready to be reviewed

**Comment by Koraytkn** [comment]
I have created a [sub-issue](https://github.com/bounswe/bounswe2022group2/issues/975) to benefit during the documentation process.

**Comment by Koraytkn** [comment]
I have also created the related pull request, which can be seen on the sub-issue that I have mentioned above.

**Comment by Koraytkn** [comment]
Related PR has been approved and merged to master, after mobile part is completed this issue can also be closed.

**Comment by ezgy** [comment]
Both mobile and web parts have been added to the report.
