### ISSUE TITLE
Final Milestone: Individual Contributions Report for Ezgi Aysel Batı

### ISSUE THREAD

**Issue by ezgy** [bounswe/bounswe2022group2#972]
### Issue Description

For the final milestone, each group member should write a report outlining their individual contributions to the project. This report should include information about the member, their specific responsibilities, any notable code contributions and management challenges they faced, pull requests submitted, and any unit tests they created. The member should complete their own section of the individual contributions report.

### Step Details

Steps that will be performed:
- [ ] Member: Info about myself
- [ ] Responsibilities
- [ ] Main contributions
- [ ] Code related significant issues
- [ ] Management related significant issues
- [ ] Pull requests: My pull requests
- [ ] Unit Tests

### Deadline of the Issue

02/01/2023

### Reviewer

None

### Deadline for the Review

02/01/2023
