### ISSUE TITLE
Frontend: UI/UX section for final milestone 

### ISSUE THREAD

**Issue by Koraytkn** [bounswe/bounswe2022group2#975]
### Issue Description

As it is requested for our team's final milestone report, I am the assignee of the front-end team for the documentation of the user interfaces. This issue is a sub-issue of the [parent issue](https://github.com/bounswe/bounswe2022group2/issues/962) which is the main issue related to the UI/UX section for the final milestone. 

### Step Details

Steps that will be performed:
- [x] Taking screenshots of all the pages in the web application.
- [x] Determining the responsible of each page. 
- [x] Providing the page implementation hyperlink for each page.

### Final Actions

After this issue is finalized the related PR will be created, the status of this issue will be mentioned in the parent issue and when the related PR is merged into the master this issue will also be closed. 

### Deadline of the Issue

02.01.2023 - 23.59

### Reviewer

Ezgi Aysel Batı

### Deadline for the Review

02.01.2023 - 23.59

**Comment by surmelienes1** [comment]
## Conclusion

Thank you @Koraytkn for your valuable contributions! Since I have merged the changes you have made with the master branch to continue working on the final milestone report, I will now close this issue.
