### ISSUE TITLE
Final Milestone: Individual Contributions Report of Egemen Atik

### ISSUE THREAD

**Issue by egemenatikk** [bounswe/bounswe2022group2#988]
### Issue Description

In the final milestone report, we are asked to add our individual contributions for milestone-1, milestone-2 and milestone-3(final milestone). This issue is opened to fix that task.

### Step Details

Steps that will be performed:
- [ ] Add personal efforts for milestone-1
- [ ] Add personal efforts for milestone-2
- [ ] Add personal efforts for milestone-3

### Final Actions

After all steps mentioned above are completed, I will open a corresponding pull request. Merging that pull request will close this issue.

### Deadline of the Issue

02.01.2023 - Monday - 23:30

### Reviewer

None
